# Generated by Django 4.1.2 on 2022-10-25 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OrdersModel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='sku_code',
            field=models.CharField(default=None, max_length=128, null=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='order_id',
            field=models.CharField(default=None, max_length=128, unique=True),
        ),
        migrations.AlterField(
            model_name='orders',
            name='p_id',
            field=models.CharField(db_index=True, default=None, max_length=128),
        ),
        migrations.AlterField(
            model_name='orders',
            name='parent_id',
            field=models.CharField(db_index=True, default=None, max_length=128),
        ),
    ]
