# Generated by Django 4.1.2 on 2022-10-26 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('OrdersModel', '0004_alter_orders_order_link'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orders',
            name='order_link',
        ),
    ]
