# Generated by Django 4.1.2 on 2022-10-27 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OrdersModel', '0006_orders_order_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='r_order_settle_status',
            field=models.CharField(default='null', max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='r_order_status',
            field=models.CharField(default='null', max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='settle_date',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='orders',
            name='settle_days',
            field=models.IntegerField(default=None, null=True),
        ),
    ]
