# Generated by Django 4.1.2 on 2022-10-27 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('OrdersModel', '0007_orders_r_order_settle_status_orders_r_order_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orders',
            name='express_delivery_time',
            field=models.DateTimeField(default=None, null=True),
        ),
    ]
