# coding: utf-8

"""
    织信开放API接口

    织信开放API接口  # noqa: E501

    OpenAPI spec version: v2
    Contact: sales@conrerstone365.cn
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class AccountMemberJoinCompanyRequest(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'account_id': 'str',
        'company_id': 'str',
        'department_list': 'list[object]',
        'role_id_list': 'list[object]'
    }

    attribute_map = {
        'account_id': 'accountId',
        'company_id': 'companyId',
        'department_list': 'departmentList',
        'role_id_list': 'roleIdList'
    }

    def __init__(self, account_id=None, company_id=None, department_list=None, role_id_list=None):  # noqa: E501
        """AccountMemberJoinCompanyRequest - a model defined in Swagger"""  # noqa: E501
        self._account_id = None
        self._company_id = None
        self._department_list = None
        self._role_id_list = None
        self.discriminator = None
        self.account_id = account_id
        self.company_id = company_id
        self.department_list = department_list
        self.role_id_list = role_id_list

    @property
    def account_id(self):
        """Gets the account_id of this AccountMemberJoinCompanyRequest.  # noqa: E501

        accountId  # noqa: E501

        :return: The account_id of this AccountMemberJoinCompanyRequest.  # noqa: E501
        :rtype: str
        """
        return self._account_id

    @account_id.setter
    def account_id(self, account_id):
        """Sets the account_id of this AccountMemberJoinCompanyRequest.

        accountId  # noqa: E501

        :param account_id: The account_id of this AccountMemberJoinCompanyRequest.  # noqa: E501
        :type: str
        """
        if account_id is None:
            raise ValueError("Invalid value for `account_id`, must not be `None`")  # noqa: E501

        self._account_id = account_id

    @property
    def company_id(self):
        """Gets the company_id of this AccountMemberJoinCompanyRequest.  # noqa: E501

        companyId  # noqa: E501

        :return: The company_id of this AccountMemberJoinCompanyRequest.  # noqa: E501
        :rtype: str
        """
        return self._company_id

    @company_id.setter
    def company_id(self, company_id):
        """Sets the company_id of this AccountMemberJoinCompanyRequest.

        companyId  # noqa: E501

        :param company_id: The company_id of this AccountMemberJoinCompanyRequest.  # noqa: E501
        :type: str
        """
        if company_id is None:
            raise ValueError("Invalid value for `company_id`, must not be `None`")  # noqa: E501

        self._company_id = company_id

    @property
    def department_list(self):
        """Gets the department_list of this AccountMemberJoinCompanyRequest.  # noqa: E501

        用户部门ID列表  # noqa: E501

        :return: The department_list of this AccountMemberJoinCompanyRequest.  # noqa: E501
        :rtype: list[object]
        """
        return self._department_list

    @department_list.setter
    def department_list(self, department_list):
        """Sets the department_list of this AccountMemberJoinCompanyRequest.

        用户部门ID列表  # noqa: E501

        :param department_list: The department_list of this AccountMemberJoinCompanyRequest.  # noqa: E501
        :type: list[object]
        """
        if department_list is None:
            raise ValueError("Invalid value for `department_list`, must not be `None`")  # noqa: E501

        self._department_list = department_list

    @property
    def role_id_list(self):
        """Gets the role_id_list of this AccountMemberJoinCompanyRequest.  # noqa: E501

        用户角色ID列表  # noqa: E501

        :return: The role_id_list of this AccountMemberJoinCompanyRequest.  # noqa: E501
        :rtype: list[object]
        """
        return self._role_id_list

    @role_id_list.setter
    def role_id_list(self, role_id_list):
        """Sets the role_id_list of this AccountMemberJoinCompanyRequest.

        用户角色ID列表  # noqa: E501

        :param role_id_list: The role_id_list of this AccountMemberJoinCompanyRequest.  # noqa: E501
        :type: list[object]
        """
        if role_id_list is None:
            raise ValueError("Invalid value for `role_id_list`, must not be `None`")  # noqa: E501

        self._role_id_list = role_id_list

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(AccountMemberJoinCompanyRequest, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, AccountMemberJoinCompanyRequest):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
