# coding: utf-8

"""
    织信开放API接口

    织信开放API接口  # noqa: E501

    OpenAPI spec version: v2
    Contact: sales@conrerstone365.cn
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class AdminAppTemplateImportFromImaFileRequest(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'ima_file_path': 'str'
    }

    attribute_map = {
        'ima_file_path': 'imaFilePath'
    }

    def __init__(self, ima_file_path=None):  # noqa: E501
        """AdminAppTemplateImportFromImaFileRequest - a model defined in Swagger"""  # noqa: E501
        self._ima_file_path = None
        self.discriminator = None
        self.ima_file_path = ima_file_path

    @property
    def ima_file_path(self):
        """Gets the ima_file_path of this AdminAppTemplateImportFromImaFileRequest.  # noqa: E501

        ima文件路径  # noqa: E501

        :return: The ima_file_path of this AdminAppTemplateImportFromImaFileRequest.  # noqa: E501
        :rtype: str
        """
        return self._ima_file_path

    @ima_file_path.setter
    def ima_file_path(self, ima_file_path):
        """Sets the ima_file_path of this AdminAppTemplateImportFromImaFileRequest.

        ima文件路径  # noqa: E501

        :param ima_file_path: The ima_file_path of this AdminAppTemplateImportFromImaFileRequest.  # noqa: E501
        :type: str
        """
        if ima_file_path is None:
            raise ValueError("Invalid value for `ima_file_path`, must not be `None`")  # noqa: E501

        self._ima_file_path = ima_file_path

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(AdminAppTemplateImportFromImaFileRequest, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, AdminAppTemplateImportFromImaFileRequest):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
