# coding: utf-8

"""
    织信开放API接口

    织信开放API接口  # noqa: E501

    OpenAPI spec version: v2
    Contact: sales@conrerstone365.cn
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class AdminAppTemplateListRequest(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'str',
        'name': 'str',
        'category_list': 'list[object]',
        'is_free': 'bool',
        'is_default': 'bool',
        'is_hidden': 'bool'
    }

    attribute_map = {
        'id': 'id',
        'name': 'name',
        'category_list': 'categoryList',
        'is_free': 'isFree',
        'is_default': 'isDefault',
        'is_hidden': 'isHidden'
    }

    def __init__(self, id=None, name=None, category_list=None, is_free=None, is_default=None, is_hidden=None):  # noqa: E501
        """AdminAppTemplateListRequest - a model defined in Swagger"""  # noqa: E501
        self._id = None
        self._name = None
        self._category_list = None
        self._is_free = None
        self._is_default = None
        self._is_hidden = None
        self.discriminator = None
        if id is not None:
            self.id = id
        if name is not None:
            self.name = name
        if category_list is not None:
            self.category_list = category_list
        if is_free is not None:
            self.is_free = is_free
        if is_default is not None:
            self.is_default = is_default
        if is_hidden is not None:
            self.is_hidden = is_hidden

    @property
    def id(self):
        """Gets the id of this AdminAppTemplateListRequest.  # noqa: E501

        id  # noqa: E501

        :return: The id of this AdminAppTemplateListRequest.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this AdminAppTemplateListRequest.

        id  # noqa: E501

        :param id: The id of this AdminAppTemplateListRequest.  # noqa: E501
        :type: str
        """

        self._id = id

    @property
    def name(self):
        """Gets the name of this AdminAppTemplateListRequest.  # noqa: E501

        名称  # noqa: E501

        :return: The name of this AdminAppTemplateListRequest.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this AdminAppTemplateListRequest.

        名称  # noqa: E501

        :param name: The name of this AdminAppTemplateListRequest.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def category_list(self):
        """Gets the category_list of this AdminAppTemplateListRequest.  # noqa: E501

        分类  # noqa: E501

        :return: The category_list of this AdminAppTemplateListRequest.  # noqa: E501
        :rtype: list[object]
        """
        return self._category_list

    @category_list.setter
    def category_list(self, category_list):
        """Sets the category_list of this AdminAppTemplateListRequest.

        分类  # noqa: E501

        :param category_list: The category_list of this AdminAppTemplateListRequest.  # noqa: E501
        :type: list[object]
        """

        self._category_list = category_list

    @property
    def is_free(self):
        """Gets the is_free of this AdminAppTemplateListRequest.  # noqa: E501

        是否免费  # noqa: E501

        :return: The is_free of this AdminAppTemplateListRequest.  # noqa: E501
        :rtype: bool
        """
        return self._is_free

    @is_free.setter
    def is_free(self, is_free):
        """Sets the is_free of this AdminAppTemplateListRequest.

        是否免费  # noqa: E501

        :param is_free: The is_free of this AdminAppTemplateListRequest.  # noqa: E501
        :type: bool
        """

        self._is_free = is_free

    @property
    def is_default(self):
        """Gets the is_default of this AdminAppTemplateListRequest.  # noqa: E501

        是否默认安装  # noqa: E501

        :return: The is_default of this AdminAppTemplateListRequest.  # noqa: E501
        :rtype: bool
        """
        return self._is_default

    @is_default.setter
    def is_default(self, is_default):
        """Sets the is_default of this AdminAppTemplateListRequest.

        是否默认安装  # noqa: E501

        :param is_default: The is_default of this AdminAppTemplateListRequest.  # noqa: E501
        :type: bool
        """

        self._is_default = is_default

    @property
    def is_hidden(self):
        """Gets the is_hidden of this AdminAppTemplateListRequest.  # noqa: E501

        是否隐藏  # noqa: E501

        :return: The is_hidden of this AdminAppTemplateListRequest.  # noqa: E501
        :rtype: bool
        """
        return self._is_hidden

    @is_hidden.setter
    def is_hidden(self, is_hidden):
        """Sets the is_hidden of this AdminAppTemplateListRequest.

        是否隐藏  # noqa: E501

        :param is_hidden: The is_hidden of this AdminAppTemplateListRequest.  # noqa: E501
        :type: bool
        """

        self._is_hidden = is_hidden

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(AdminAppTemplateListRequest, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, AdminAppTemplateListRequest):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
