# coding: utf-8

"""
    织信开放API接口

    织信开放API接口  # noqa: E501

    OpenAPI spec version: v2
    Contact: sales@conrerstone365.cn
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class AppMemberCreateRequest(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'account_id': 'str',
        'role_id_list': 'list[object]',
        'group_id_list': 'list[object]'
    }

    attribute_map = {
        'account_id': 'accountId',
        'role_id_list': 'roleIdList',
        'group_id_list': 'groupIdList'
    }

    def __init__(self, account_id=None, role_id_list=None, group_id_list=None):  # noqa: E501
        """AppMemberCreateRequest - a model defined in Swagger"""  # noqa: E501
        self._account_id = None
        self._role_id_list = None
        self._group_id_list = None
        self.discriminator = None
        self.account_id = account_id
        if role_id_list is not None:
            self.role_id_list = role_id_list
        if group_id_list is not None:
            self.group_id_list = group_id_list

    @property
    def account_id(self):
        """Gets the account_id of this AppMemberCreateRequest.  # noqa: E501

        账号ID  # noqa: E501

        :return: The account_id of this AppMemberCreateRequest.  # noqa: E501
        :rtype: str
        """
        return self._account_id

    @account_id.setter
    def account_id(self, account_id):
        """Sets the account_id of this AppMemberCreateRequest.

        账号ID  # noqa: E501

        :param account_id: The account_id of this AppMemberCreateRequest.  # noqa: E501
        :type: str
        """
        if account_id is None:
            raise ValueError("Invalid value for `account_id`, must not be `None`")  # noqa: E501

        self._account_id = account_id

    @property
    def role_id_list(self):
        """Gets the role_id_list of this AppMemberCreateRequest.  # noqa: E501

        角色ID列表  # noqa: E501

        :return: The role_id_list of this AppMemberCreateRequest.  # noqa: E501
        :rtype: list[object]
        """
        return self._role_id_list

    @role_id_list.setter
    def role_id_list(self, role_id_list):
        """Sets the role_id_list of this AppMemberCreateRequest.

        角色ID列表  # noqa: E501

        :param role_id_list: The role_id_list of this AppMemberCreateRequest.  # noqa: E501
        :type: list[object]
        """

        self._role_id_list = role_id_list

    @property
    def group_id_list(self):
        """Gets the group_id_list of this AppMemberCreateRequest.  # noqa: E501

        分组ID列表  # noqa: E501

        :return: The group_id_list of this AppMemberCreateRequest.  # noqa: E501
        :rtype: list[object]
        """
        return self._group_id_list

    @group_id_list.setter
    def group_id_list(self, group_id_list):
        """Sets the group_id_list of this AppMemberCreateRequest.

        分组ID列表  # noqa: E501

        :param group_id_list: The group_id_list of this AppMemberCreateRequest.  # noqa: E501
        :type: list[object]
        """

        self._group_id_list = group_id_list

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(AppMemberCreateRequest, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, AppMemberCreateRequest):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
