# coding: utf-8

"""
    织信开放API接口

    织信开放API接口  # noqa: E501

    OpenAPI spec version: v2
    Contact: sales@conrerstone365.cn
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class CompanyTokenRequest(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'company_id': 'str',
        'company_secret': 'str'
    }

    attribute_map = {
        'company_id': 'companyId',
        'company_secret': 'companySecret'
    }

    def __init__(self, company_id=None, company_secret=None):  # noqa: E501
        """CompanyTokenRequest - a model defined in Swagger"""  # noqa: E501
        self._company_id = None
        self._company_secret = None
        self.discriminator = None
        self.company_id = company_id
        self.company_secret = company_secret

    @property
    def company_id(self):
        """Gets the company_id of this CompanyTokenRequest.  # noqa: E501

        团队ID  # noqa: E501

        :return: The company_id of this CompanyTokenRequest.  # noqa: E501
        :rtype: str
        """
        return self._company_id

    @company_id.setter
    def company_id(self, company_id):
        """Sets the company_id of this CompanyTokenRequest.

        团队ID  # noqa: E501

        :param company_id: The company_id of this CompanyTokenRequest.  # noqa: E501
        :type: str
        """
        if company_id is None:
            raise ValueError("Invalid value for `company_id`, must not be `None`")  # noqa: E501

        self._company_id = company_id

    @property
    def company_secret(self):
        """Gets the company_secret of this CompanyTokenRequest.  # noqa: E501

        团队凭证密钥  # noqa: E501

        :return: The company_secret of this CompanyTokenRequest.  # noqa: E501
        :rtype: str
        """
        return self._company_secret

    @company_secret.setter
    def company_secret(self, company_secret):
        """Sets the company_secret of this CompanyTokenRequest.

        团队凭证密钥  # noqa: E501

        :param company_secret: The company_secret of this CompanyTokenRequest.  # noqa: E501
        :type: str
        """
        if company_secret is None:
            raise ValueError("Invalid value for `company_secret`, must not be `None`")  # noqa: E501

        self._company_secret = company_secret

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(CompanyTokenRequest, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, CompanyTokenRequest):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
