# coding: utf-8

"""
    织信开放API接口

    织信开放API接口  # noqa: E501

    OpenAPI spec version: v2
    Contact: sales@conrerstone365.cn
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class CompanyMemberRoleListRequest(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'name': 'str',
        'page_size': 'int',
        'page_index': 'int'
    }

    attribute_map = {
        'name': 'name',
        'page_size': 'pageSize',
        'page_index': 'pageIndex'
    }

    def __init__(self, name=None, page_size=None, page_index=None):  # noqa: E501
        """CompanyMemberRoleListRequest - a model defined in Swagger"""  # noqa: E501
        self._name = None
        self._page_size = None
        self._page_index = None
        self.discriminator = None
        if name is not None:
            self.name = name
        if page_size is not None:
            self.page_size = page_size
        if page_index is not None:
            self.page_index = page_index

    @property
    def name(self):
        """Gets the name of this CompanyMemberRoleListRequest.  # noqa: E501

        名称  # noqa: E501

        :return: The name of this CompanyMemberRoleListRequest.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this CompanyMemberRoleListRequest.

        名称  # noqa: E501

        :param name: The name of this CompanyMemberRoleListRequest.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def page_size(self):
        """Gets the page_size of this CompanyMemberRoleListRequest.  # noqa: E501

        每页数量  # noqa: E501

        :return: The page_size of this CompanyMemberRoleListRequest.  # noqa: E501
        :rtype: int
        """
        return self._page_size

    @page_size.setter
    def page_size(self, page_size):
        """Sets the page_size of this CompanyMemberRoleListRequest.

        每页数量  # noqa: E501

        :param page_size: The page_size of this CompanyMemberRoleListRequest.  # noqa: E501
        :type: int
        """

        self._page_size = page_size

    @property
    def page_index(self):
        """Gets the page_index of this CompanyMemberRoleListRequest.  # noqa: E501

        页码  # noqa: E501

        :return: The page_index of this CompanyMemberRoleListRequest.  # noqa: E501
        :rtype: int
        """
        return self._page_index

    @page_index.setter
    def page_index(self, page_index):
        """Sets the page_index of this CompanyMemberRoleListRequest.

        页码  # noqa: E501

        :param page_index: The page_index of this CompanyMemberRoleListRequest.  # noqa: E501
        :type: int
        """

        self._page_index = page_index

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(CompanyMemberRoleListRequest, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, CompanyMemberRoleListRequest):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
