# coding: utf-8

"""
    织信开放API接口

    织信开放API接口  # noqa: E501

    OpenAPI spec version: v2
    Contact: sales@conrerstone365.cn
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class CompanyDepartmentUpdateRequest(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'id': 'str',
        'name': 'str',
        'parent_id': 'str',
        'remark': 'str',
        'owner_id_list': 'list[object]',
        'short_name': 'str'
    }

    attribute_map = {
        'id': 'id',
        'name': 'name',
        'parent_id': 'parentId',
        'remark': 'remark',
        'owner_id_list': 'ownerIdList',
        'short_name': 'shortName'
    }

    def __init__(self, id=None, name=None, parent_id=None, remark=None, owner_id_list=None, short_name=None):  # noqa: E501
        """CompanyDepartmentUpdateRequest - a model defined in Swagger"""  # noqa: E501
        self._id = None
        self._name = None
        self._parent_id = None
        self._remark = None
        self._owner_id_list = None
        self._short_name = None
        self.discriminator = None
        self.id = id
        if name is not None:
            self.name = name
        if parent_id is not None:
            self.parent_id = parent_id
        if remark is not None:
            self.remark = remark
        if owner_id_list is not None:
            self.owner_id_list = owner_id_list
        if short_name is not None:
            self.short_name = short_name

    @property
    def id(self):
        """Gets the id of this CompanyDepartmentUpdateRequest.  # noqa: E501

        id  # noqa: E501

        :return: The id of this CompanyDepartmentUpdateRequest.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this CompanyDepartmentUpdateRequest.

        id  # noqa: E501

        :param id: The id of this CompanyDepartmentUpdateRequest.  # noqa: E501
        :type: str
        """
        if id is None:
            raise ValueError("Invalid value for `id`, must not be `None`")  # noqa: E501

        self._id = id

    @property
    def name(self):
        """Gets the name of this CompanyDepartmentUpdateRequest.  # noqa: E501

        名称  # noqa: E501

        :return: The name of this CompanyDepartmentUpdateRequest.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this CompanyDepartmentUpdateRequest.

        名称  # noqa: E501

        :param name: The name of this CompanyDepartmentUpdateRequest.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def parent_id(self):
        """Gets the parent_id of this CompanyDepartmentUpdateRequest.  # noqa: E501

        父id  # noqa: E501

        :return: The parent_id of this CompanyDepartmentUpdateRequest.  # noqa: E501
        :rtype: str
        """
        return self._parent_id

    @parent_id.setter
    def parent_id(self, parent_id):
        """Sets the parent_id of this CompanyDepartmentUpdateRequest.

        父id  # noqa: E501

        :param parent_id: The parent_id of this CompanyDepartmentUpdateRequest.  # noqa: E501
        :type: str
        """

        self._parent_id = parent_id

    @property
    def remark(self):
        """Gets the remark of this CompanyDepartmentUpdateRequest.  # noqa: E501

        备注  # noqa: E501

        :return: The remark of this CompanyDepartmentUpdateRequest.  # noqa: E501
        :rtype: str
        """
        return self._remark

    @remark.setter
    def remark(self, remark):
        """Sets the remark of this CompanyDepartmentUpdateRequest.

        备注  # noqa: E501

        :param remark: The remark of this CompanyDepartmentUpdateRequest.  # noqa: E501
        :type: str
        """

        self._remark = remark

    @property
    def owner_id_list(self):
        """Gets the owner_id_list of this CompanyDepartmentUpdateRequest.  # noqa: E501

        负责人列表  # noqa: E501

        :return: The owner_id_list of this CompanyDepartmentUpdateRequest.  # noqa: E501
        :rtype: list[object]
        """
        return self._owner_id_list

    @owner_id_list.setter
    def owner_id_list(self, owner_id_list):
        """Sets the owner_id_list of this CompanyDepartmentUpdateRequest.

        负责人列表  # noqa: E501

        :param owner_id_list: The owner_id_list of this CompanyDepartmentUpdateRequest.  # noqa: E501
        :type: list[object]
        """

        self._owner_id_list = owner_id_list

    @property
    def short_name(self):
        """Gets the short_name of this CompanyDepartmentUpdateRequest.  # noqa: E501

        简称  # noqa: E501

        :return: The short_name of this CompanyDepartmentUpdateRequest.  # noqa: E501
        :rtype: str
        """
        return self._short_name

    @short_name.setter
    def short_name(self, short_name):
        """Sets the short_name of this CompanyDepartmentUpdateRequest.

        简称  # noqa: E501

        :param short_name: The short_name of this CompanyDepartmentUpdateRequest.  # noqa: E501
        :type: str
        """

        self._short_name = short_name

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(CompanyDepartmentUpdateRequest, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, CompanyDepartmentUpdateRequest):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
