# coding: utf-8

"""
    织信开放API接口

    织信开放API接口  # noqa: E501

    OpenAPI spec version: v2
    Contact: sales@conrerstone365.cn
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class TableWorkflowInstanceVO(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'table_id': 'str',
        'record_id': 'str',
        'workflow_id': 'str',
        'title': 'str',
        'is_finished': 'bool',
        'finish_type': 'str',
        'finish_text': 'str',
        'finish_time': 'float',
        'form_data': 'dict(str, object)',
        'remark': 'str',
        'owner_account_list': 'list[TableAccountSimple]',
        'cc_account_list': 'list[TableAccountSimple]',
        'chart_id': 'str',
        'chart_version': 'int',
        'owner_config': 'TableWorkflowInstanceOwnerConfig',
        'status': 'int',
        'module_name': 'str',
        'module_icon': 'str',
        'id': 'str',
        'company_id': 'str',
        'application_id': 'str',
        'create_time': 'float',
        'update_time': 'float',
        'create_account_id': 'str',
        'create_account_name': 'str',
        'update_account_id': 'str',
        'update_account_name': 'str',
        'app_name': 'str',
        'app_color': 'str',
        'app_icon': 'str',
        'is_delete': 'bool'
    }

    attribute_map = {
        'table_id': 'tableId',
        'record_id': 'recordId',
        'workflow_id': 'workflowId',
        'title': 'title',
        'is_finished': 'isFinished',
        'finish_type': 'finishType',
        'finish_text': 'finishText',
        'finish_time': 'finishTime',
        'form_data': 'formData',
        'remark': 'remark',
        'owner_account_list': 'ownerAccountList',
        'cc_account_list': 'ccAccountList',
        'chart_id': 'chartId',
        'chart_version': 'chartVersion',
        'owner_config': 'ownerConfig',
        'status': 'status',
        'module_name': 'moduleName',
        'module_icon': 'moduleIcon',
        'id': 'id',
        'company_id': 'companyId',
        'application_id': 'applicationId',
        'create_time': 'createTime',
        'update_time': 'updateTime',
        'create_account_id': 'createAccountId',
        'create_account_name': 'createAccountName',
        'update_account_id': 'updateAccountId',
        'update_account_name': 'updateAccountName',
        'app_name': 'appName',
        'app_color': 'appColor',
        'app_icon': 'appIcon',
        'is_delete': 'isDelete'
    }

    def __init__(self, table_id=None, record_id=None, workflow_id=None, title=None, is_finished=None, finish_type=None, finish_text=None, finish_time=None, form_data=None, remark=None, owner_account_list=None, cc_account_list=None, chart_id=None, chart_version=None, owner_config=None, status=None, module_name=None, module_icon=None, id=None, company_id=None, application_id=None, create_time=None, update_time=None, create_account_id=None, create_account_name=None, update_account_id=None, update_account_name=None, app_name=None, app_color=None, app_icon=None, is_delete=None):  # noqa: E501
        """TableWorkflowInstanceVO - a model defined in Swagger"""  # noqa: E501
        self._table_id = None
        self._record_id = None
        self._workflow_id = None
        self._title = None
        self._is_finished = None
        self._finish_type = None
        self._finish_text = None
        self._finish_time = None
        self._form_data = None
        self._remark = None
        self._owner_account_list = None
        self._cc_account_list = None
        self._chart_id = None
        self._chart_version = None
        self._owner_config = None
        self._status = None
        self._module_name = None
        self._module_icon = None
        self._id = None
        self._company_id = None
        self._application_id = None
        self._create_time = None
        self._update_time = None
        self._create_account_id = None
        self._create_account_name = None
        self._update_account_id = None
        self._update_account_name = None
        self._app_name = None
        self._app_color = None
        self._app_icon = None
        self._is_delete = None
        self.discriminator = None
        if table_id is not None:
            self.table_id = table_id
        if record_id is not None:
            self.record_id = record_id
        if workflow_id is not None:
            self.workflow_id = workflow_id
        if title is not None:
            self.title = title
        if is_finished is not None:
            self.is_finished = is_finished
        if finish_type is not None:
            self.finish_type = finish_type
        if finish_text is not None:
            self.finish_text = finish_text
        if finish_time is not None:
            self.finish_time = finish_time
        if form_data is not None:
            self.form_data = form_data
        if remark is not None:
            self.remark = remark
        if owner_account_list is not None:
            self.owner_account_list = owner_account_list
        if cc_account_list is not None:
            self.cc_account_list = cc_account_list
        if chart_id is not None:
            self.chart_id = chart_id
        if chart_version is not None:
            self.chart_version = chart_version
        if owner_config is not None:
            self.owner_config = owner_config
        if status is not None:
            self.status = status
        if module_name is not None:
            self.module_name = module_name
        if module_icon is not None:
            self.module_icon = module_icon
        if id is not None:
            self.id = id
        if company_id is not None:
            self.company_id = company_id
        if application_id is not None:
            self.application_id = application_id
        if create_time is not None:
            self.create_time = create_time
        if update_time is not None:
            self.update_time = update_time
        if create_account_id is not None:
            self.create_account_id = create_account_id
        if create_account_name is not None:
            self.create_account_name = create_account_name
        if update_account_id is not None:
            self.update_account_id = update_account_id
        if update_account_name is not None:
            self.update_account_name = update_account_name
        if app_name is not None:
            self.app_name = app_name
        if app_color is not None:
            self.app_color = app_color
        if app_icon is not None:
            self.app_icon = app_icon
        if is_delete is not None:
            self.is_delete = is_delete

    @property
    def table_id(self):
        """Gets the table_id of this TableWorkflowInstanceVO.  # noqa: E501

        数据表ID  # noqa: E501

        :return: The table_id of this TableWorkflowInstanceVO.  # noqa: E501
        :rtype: str
        """
        return self._table_id

    @table_id.setter
    def table_id(self, table_id):
        """Sets the table_id of this TableWorkflowInstanceVO.

        数据表ID  # noqa: E501

        :param table_id: The table_id of this TableWorkflowInstanceVO.  # noqa: E501
        :type: str
        """

        self._table_id = table_id

    @property
    def record_id(self):
        """Gets the record_id of this TableWorkflowInstanceVO.  # noqa: E501

        记录ID  # noqa: E501

        :return: The record_id of this TableWorkflowInstanceVO.  # noqa: E501
        :rtype: str
        """
        return self._record_id

    @record_id.setter
    def record_id(self, record_id):
        """Sets the record_id of this TableWorkflowInstanceVO.

        记录ID  # noqa: E501

        :param record_id: The record_id of this TableWorkflowInstanceVO.  # noqa: E501
        :type: str
        """

        self._record_id = record_id

    @property
    def workflow_id(self):
        """Gets the workflow_id of this TableWorkflowInstanceVO.  # noqa: E501

        流程定义ID  # noqa: E501

        :return: The workflow_id of this TableWorkflowInstanceVO.  # noqa: E501
        :rtype: str
        """
        return self._workflow_id

    @workflow_id.setter
    def workflow_id(self, workflow_id):
        """Sets the workflow_id of this TableWorkflowInstanceVO.

        流程定义ID  # noqa: E501

        :param workflow_id: The workflow_id of this TableWorkflowInstanceVO.  # noqa: E501
        :type: str
        """

        self._workflow_id = workflow_id

    @property
    def title(self):
        """Gets the title of this TableWorkflowInstanceVO.  # noqa: E501

        标题  # noqa: E501

        :return: The title of this TableWorkflowInstanceVO.  # noqa: E501
        :rtype: str
        """
        return self._title

    @title.setter
    def title(self, title):
        """Sets the title of this TableWorkflowInstanceVO.

        标题  # noqa: E501

        :param title: The title of this TableWorkflowInstanceVO.  # noqa: E501
        :type: str
        """

        self._title = title

    @property
    def is_finished(self):
        """Gets the is_finished of this TableWorkflowInstanceVO.  # noqa: E501

        是否结束  # noqa: E501

        :return: The is_finished of this TableWorkflowInstanceVO.  # noqa: E501
        :rtype: bool
        """
        return self._is_finished

    @is_finished.setter
    def is_finished(self, is_finished):
        """Sets the is_finished of this TableWorkflowInstanceVO.

        是否结束  # noqa: E501

        :param is_finished: The is_finished of this TableWorkflowInstanceVO.  # noqa: E501
        :type: bool
        """

        self._is_finished = is_finished

    @property
    def finish_type(self):
        """Gets the finish_type of this TableWorkflowInstanceVO.  # noqa: E501

        结束类型   # noqa: E501

        :return: The finish_type of this TableWorkflowInstanceVO.  # noqa: E501
        :rtype: str
        """
        return self._finish_type

    @finish_type.setter
    def finish_type(self, finish_type):
        """Sets the finish_type of this TableWorkflowInstanceVO.

        结束类型   # noqa: E501

        :param finish_type: The finish_type of this TableWorkflowInstanceVO.  # noqa: E501
        :type: str
        """
        allowed_values = ["Finish", "Terminate", "Cancel"]  # noqa: E501
        if finish_type not in allowed_values:
            raise ValueError(
                "Invalid value for `finish_type` ({0}), must be one of {1}"  # noqa: E501
                .format(finish_type, allowed_values)
            )

        self._finish_type = finish_type

    @property
    def finish_text(self):
        """Gets the finish_text of this TableWorkflowInstanceVO.  # noqa: E501

        结束文本  # noqa: E501

        :return: The finish_text of this TableWorkflowInstanceVO.  # noqa: E501
        :rtype: str
        """
        return self._finish_text

    @finish_text.setter
    def finish_text(self, finish_text):
        """Sets the finish_text of this TableWorkflowInstanceVO.

        结束文本  # noqa: E501

        :param finish_text: The finish_text of this TableWorkflowInstanceVO.  # noqa: E501
        :type: str
        """

        self._finish_text = finish_text

    @property
    def finish_time(self):
        """Gets the finish_time of this TableWorkflowInstanceVO.  # noqa: E501

        结束时间  # noqa: E501

        :return: The finish_time of this TableWorkflowInstanceVO.  # noqa: E501
        :rtype: float
        """
        return self._finish_time

    @finish_time.setter
    def finish_time(self, finish_time):
        """Sets the finish_time of this TableWorkflowInstanceVO.

        结束时间  # noqa: E501

        :param finish_time: The finish_time of this TableWorkflowInstanceVO.  # noqa: E501
        :type: float
        """

        self._finish_time = finish_time

    @property
    def form_data(self):
        """Gets the form_data of this TableWorkflowInstanceVO.  # noqa: E501

        表单数据  # noqa: E501

        :return: The form_data of this TableWorkflowInstanceVO.  # noqa: E501
        :rtype: dict(str, object)
        """
        return self._form_data

    @form_data.setter
    def form_data(self, form_data):
        """Sets the form_data of this TableWorkflowInstanceVO.

        表单数据  # noqa: E501

        :param form_data: The form_data of this TableWorkflowInstanceVO.  # noqa: E501
        :type: dict(str, object)
        """

        self._form_data = form_data

    @property
    def remark(self):
        """Gets the remark of this TableWorkflowInstanceVO.  # noqa: E501

        描述  # noqa: E501

        :return: The remark of this TableWorkflowInstanceVO.  # noqa: E501
        :rtype: str
        """
        return self._remark

    @remark.setter
    def remark(self, remark):
        """Sets the remark of this TableWorkflowInstanceVO.

        描述  # noqa: E501

        :param remark: The remark of this TableWorkflowInstanceVO.  # noqa: E501
        :type: str
        """

        self._remark = remark

    @property
    def owner_account_list(self):
        """Gets the owner_account_list of this TableWorkflowInstanceVO.  # noqa: E501

        当前责任人列表  # noqa: E501

        :return: The owner_account_list of this TableWorkflowInstanceVO.  # noqa: E501
        :rtype: list[TableAccountSimple]
        """
        return self._owner_account_list

    @owner_account_list.setter
    def owner_account_list(self, owner_account_list):
        """Sets the owner_account_list of this TableWorkflowInstanceVO.

        当前责任人列表  # noqa: E501

        :param owner_account_list: The owner_account_list of this TableWorkflowInstanceVO.  # noqa: E501
        :type: list[TableAccountSimple]
        """

        self._owner_account_list = owner_account_list

    @property
    def cc_account_list(self):
        """Gets the cc_account_list of this TableWorkflowInstanceVO.  # noqa: E501

        抄送人列表  # noqa: E501

        :return: The cc_account_list of this TableWorkflowInstanceVO.  # noqa: E501
        :rtype: list[TableAccountSimple]
        """
        return self._cc_account_list

    @cc_account_list.setter
    def cc_account_list(self, cc_account_list):
        """Sets the cc_account_list of this TableWorkflowInstanceVO.

        抄送人列表  # noqa: E501

        :param cc_account_list: The cc_account_list of this TableWorkflowInstanceVO.  # noqa: E501
        :type: list[TableAccountSimple]
        """

        self._cc_account_list = cc_account_list

    @property
    def chart_id(self):
        """Gets the chart_id of this TableWorkflowInstanceVO.  # noqa: E501

        流程图ID  # noqa: E501

        :return: The chart_id of this TableWorkflowInstanceVO.  # noqa: E501
        :rtype: str
        """
        return self._chart_id

    @chart_id.setter
    def chart_id(self, chart_id):
        """Sets the chart_id of this TableWorkflowInstanceVO.

        流程图ID  # noqa: E501

        :param chart_id: The chart_id of this TableWorkflowInstanceVO.  # noqa: E501
        :type: str
        """

        self._chart_id = chart_id

    @property
    def chart_version(self):
        """Gets the chart_version of this TableWorkflowInstanceVO.  # noqa: E501

        流程图版本  # noqa: E501

        :return: The chart_version of this TableWorkflowInstanceVO.  # noqa: E501
        :rtype: int
        """
        return self._chart_version

    @chart_version.setter
    def chart_version(self, chart_version):
        """Sets the chart_version of this TableWorkflowInstanceVO.

        流程图版本  # noqa: E501

        :param chart_version: The chart_version of this TableWorkflowInstanceVO.  # noqa: E501
        :type: int
        """

        self._chart_version = chart_version

    @property
    def owner_config(self):
        """Gets the owner_config of this TableWorkflowInstanceVO.  # noqa: E501


        :return: The owner_config of this TableWorkflowInstanceVO.  # noqa: E501
        :rtype: TableWorkflowInstanceOwnerConfig
        """
        return self._owner_config

    @owner_config.setter
    def owner_config(self, owner_config):
        """Sets the owner_config of this TableWorkflowInstanceVO.


        :param owner_config: The owner_config of this TableWorkflowInstanceVO.  # noqa: E501
        :type: TableWorkflowInstanceOwnerConfig
        """

        self._owner_config = owner_config

    @property
    def status(self):
        """Gets the status of this TableWorkflowInstanceVO.  # noqa: E501

        状态  # noqa: E501

        :return: The status of this TableWorkflowInstanceVO.  # noqa: E501
        :rtype: int
        """
        return self._status

    @status.setter
    def status(self, status):
        """Sets the status of this TableWorkflowInstanceVO.

        状态  # noqa: E501

        :param status: The status of this TableWorkflowInstanceVO.  # noqa: E501
        :type: int
        """
        allowed_values = [1, 2, 3, 4, 5]  # noqa: E501
        if status not in allowed_values:
            raise ValueError(
                "Invalid value for `status` ({0}), must be one of {1}"  # noqa: E501
                .format(status, allowed_values)
            )

        self._status = status

    @property
    def module_name(self):
        """Gets the module_name of this TableWorkflowInstanceVO.  # noqa: E501

        模块名称  # noqa: E501

        :return: The module_name of this TableWorkflowInstanceVO.  # noqa: E501
        :rtype: str
        """
        return self._module_name

    @module_name.setter
    def module_name(self, module_name):
        """Sets the module_name of this TableWorkflowInstanceVO.

        模块名称  # noqa: E501

        :param module_name: The module_name of this TableWorkflowInstanceVO.  # noqa: E501
        :type: str
        """

        self._module_name = module_name

    @property
    def module_icon(self):
        """Gets the module_icon of this TableWorkflowInstanceVO.  # noqa: E501

        模块图标  # noqa: E501

        :return: The module_icon of this TableWorkflowInstanceVO.  # noqa: E501
        :rtype: str
        """
        return self._module_icon

    @module_icon.setter
    def module_icon(self, module_icon):
        """Sets the module_icon of this TableWorkflowInstanceVO.

        模块图标  # noqa: E501

        :param module_icon: The module_icon of this TableWorkflowInstanceVO.  # noqa: E501
        :type: str
        """

        self._module_icon = module_icon

    @property
    def id(self):
        """Gets the id of this TableWorkflowInstanceVO.  # noqa: E501

        ID  # noqa: E501

        :return: The id of this TableWorkflowInstanceVO.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this TableWorkflowInstanceVO.

        ID  # noqa: E501

        :param id: The id of this TableWorkflowInstanceVO.  # noqa: E501
        :type: str
        """

        self._id = id

    @property
    def company_id(self):
        """Gets the company_id of this TableWorkflowInstanceVO.  # noqa: E501

        团队ID  # noqa: E501

        :return: The company_id of this TableWorkflowInstanceVO.  # noqa: E501
        :rtype: str
        """
        return self._company_id

    @company_id.setter
    def company_id(self, company_id):
        """Sets the company_id of this TableWorkflowInstanceVO.

        团队ID  # noqa: E501

        :param company_id: The company_id of this TableWorkflowInstanceVO.  # noqa: E501
        :type: str
        """

        self._company_id = company_id

    @property
    def application_id(self):
        """Gets the application_id of this TableWorkflowInstanceVO.  # noqa: E501

        应用ID  # noqa: E501

        :return: The application_id of this TableWorkflowInstanceVO.  # noqa: E501
        :rtype: str
        """
        return self._application_id

    @application_id.setter
    def application_id(self, application_id):
        """Sets the application_id of this TableWorkflowInstanceVO.

        应用ID  # noqa: E501

        :param application_id: The application_id of this TableWorkflowInstanceVO.  # noqa: E501
        :type: str
        """

        self._application_id = application_id

    @property
    def create_time(self):
        """Gets the create_time of this TableWorkflowInstanceVO.  # noqa: E501

        创建时间  # noqa: E501

        :return: The create_time of this TableWorkflowInstanceVO.  # noqa: E501
        :rtype: float
        """
        return self._create_time

    @create_time.setter
    def create_time(self, create_time):
        """Sets the create_time of this TableWorkflowInstanceVO.

        创建时间  # noqa: E501

        :param create_time: The create_time of this TableWorkflowInstanceVO.  # noqa: E501
        :type: float
        """

        self._create_time = create_time

    @property
    def update_time(self):
        """Gets the update_time of this TableWorkflowInstanceVO.  # noqa: E501

        最后更新时间  # noqa: E501

        :return: The update_time of this TableWorkflowInstanceVO.  # noqa: E501
        :rtype: float
        """
        return self._update_time

    @update_time.setter
    def update_time(self, update_time):
        """Sets the update_time of this TableWorkflowInstanceVO.

        最后更新时间  # noqa: E501

        :param update_time: The update_time of this TableWorkflowInstanceVO.  # noqa: E501
        :type: float
        """

        self._update_time = update_time

    @property
    def create_account_id(self):
        """Gets the create_account_id of this TableWorkflowInstanceVO.  # noqa: E501

        创建人ID  # noqa: E501

        :return: The create_account_id of this TableWorkflowInstanceVO.  # noqa: E501
        :rtype: str
        """
        return self._create_account_id

    @create_account_id.setter
    def create_account_id(self, create_account_id):
        """Sets the create_account_id of this TableWorkflowInstanceVO.

        创建人ID  # noqa: E501

        :param create_account_id: The create_account_id of this TableWorkflowInstanceVO.  # noqa: E501
        :type: str
        """

        self._create_account_id = create_account_id

    @property
    def create_account_name(self):
        """Gets the create_account_name of this TableWorkflowInstanceVO.  # noqa: E501

        创建人名称  # noqa: E501

        :return: The create_account_name of this TableWorkflowInstanceVO.  # noqa: E501
        :rtype: str
        """
        return self._create_account_name

    @create_account_name.setter
    def create_account_name(self, create_account_name):
        """Sets the create_account_name of this TableWorkflowInstanceVO.

        创建人名称  # noqa: E501

        :param create_account_name: The create_account_name of this TableWorkflowInstanceVO.  # noqa: E501
        :type: str
        """

        self._create_account_name = create_account_name

    @property
    def update_account_id(self):
        """Gets the update_account_id of this TableWorkflowInstanceVO.  # noqa: E501

        最后更新人ID  # noqa: E501

        :return: The update_account_id of this TableWorkflowInstanceVO.  # noqa: E501
        :rtype: str
        """
        return self._update_account_id

    @update_account_id.setter
    def update_account_id(self, update_account_id):
        """Sets the update_account_id of this TableWorkflowInstanceVO.

        最后更新人ID  # noqa: E501

        :param update_account_id: The update_account_id of this TableWorkflowInstanceVO.  # noqa: E501
        :type: str
        """

        self._update_account_id = update_account_id

    @property
    def update_account_name(self):
        """Gets the update_account_name of this TableWorkflowInstanceVO.  # noqa: E501

        最后更新人名称  # noqa: E501

        :return: The update_account_name of this TableWorkflowInstanceVO.  # noqa: E501
        :rtype: str
        """
        return self._update_account_name

    @update_account_name.setter
    def update_account_name(self, update_account_name):
        """Sets the update_account_name of this TableWorkflowInstanceVO.

        最后更新人名称  # noqa: E501

        :param update_account_name: The update_account_name of this TableWorkflowInstanceVO.  # noqa: E501
        :type: str
        """

        self._update_account_name = update_account_name

    @property
    def app_name(self):
        """Gets the app_name of this TableWorkflowInstanceVO.  # noqa: E501

        应用名称  # noqa: E501

        :return: The app_name of this TableWorkflowInstanceVO.  # noqa: E501
        :rtype: str
        """
        return self._app_name

    @app_name.setter
    def app_name(self, app_name):
        """Sets the app_name of this TableWorkflowInstanceVO.

        应用名称  # noqa: E501

        :param app_name: The app_name of this TableWorkflowInstanceVO.  # noqa: E501
        :type: str
        """

        self._app_name = app_name

    @property
    def app_color(self):
        """Gets the app_color of this TableWorkflowInstanceVO.  # noqa: E501

        应用颜色  # noqa: E501

        :return: The app_color of this TableWorkflowInstanceVO.  # noqa: E501
        :rtype: str
        """
        return self._app_color

    @app_color.setter
    def app_color(self, app_color):
        """Sets the app_color of this TableWorkflowInstanceVO.

        应用颜色  # noqa: E501

        :param app_color: The app_color of this TableWorkflowInstanceVO.  # noqa: E501
        :type: str
        """

        self._app_color = app_color

    @property
    def app_icon(self):
        """Gets the app_icon of this TableWorkflowInstanceVO.  # noqa: E501

        应用图标  # noqa: E501

        :return: The app_icon of this TableWorkflowInstanceVO.  # noqa: E501
        :rtype: str
        """
        return self._app_icon

    @app_icon.setter
    def app_icon(self, app_icon):
        """Sets the app_icon of this TableWorkflowInstanceVO.

        应用图标  # noqa: E501

        :param app_icon: The app_icon of this TableWorkflowInstanceVO.  # noqa: E501
        :type: str
        """

        self._app_icon = app_icon

    @property
    def is_delete(self):
        """Gets the is_delete of this TableWorkflowInstanceVO.  # noqa: E501

        是否已删除  # noqa: E501

        :return: The is_delete of this TableWorkflowInstanceVO.  # noqa: E501
        :rtype: bool
        """
        return self._is_delete

    @is_delete.setter
    def is_delete(self, is_delete):
        """Sets the is_delete of this TableWorkflowInstanceVO.

        是否已删除  # noqa: E501

        :param is_delete: The is_delete of this TableWorkflowInstanceVO.  # noqa: E501
        :type: bool
        """

        self._is_delete = is_delete

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(TableWorkflowInstanceVO, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, TableWorkflowInstanceVO):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
