# coding: utf-8

"""
    织信开放API接口

    织信开放API接口  # noqa: E501

    OpenAPI spec version: v2
    Contact: sales@conrerstone365.cn
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class TableInfoVO(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'table': 'TableVO',
        'table_field_list': 'list[TableFieldVO]'
    }

    attribute_map = {
        'table': 'table',
        'table_field_list': 'tableFieldList'
    }

    def __init__(self, table=None, table_field_list=None):  # noqa: E501
        """TableInfoVO - a model defined in Swagger"""  # noqa: E501
        self._table = None
        self._table_field_list = None
        self.discriminator = None
        if table is not None:
            self.table = table
        if table_field_list is not None:
            self.table_field_list = table_field_list

    @property
    def table(self):
        """Gets the table of this TableInfoVO.  # noqa: E501


        :return: The table of this TableInfoVO.  # noqa: E501
        :rtype: TableVO
        """
        return self._table

    @table.setter
    def table(self, table):
        """Sets the table of this TableInfoVO.


        :param table: The table of this TableInfoVO.  # noqa: E501
        :type: TableVO
        """

        self._table = table

    @property
    def table_field_list(self):
        """Gets the table_field_list of this TableInfoVO.  # noqa: E501

        数据表字段列表  # noqa: E501

        :return: The table_field_list of this TableInfoVO.  # noqa: E501
        :rtype: list[TableFieldVO]
        """
        return self._table_field_list

    @table_field_list.setter
    def table_field_list(self, table_field_list):
        """Sets the table_field_list of this TableInfoVO.

        数据表字段列表  # noqa: E501

        :param table_field_list: The table_field_list of this TableInfoVO.  # noqa: E501
        :type: list[TableFieldVO]
        """

        self._table_field_list = table_field_list

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(TableInfoVO, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, TableInfoVO):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
