# coding: utf-8

"""
    织信开放API接口

    织信开放API接口  # noqa: E501

    OpenAPI spec version: v2
    Contact: sales@conrerstone365.cn
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class TableWorkflowVO(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'table_id': 'str',
        'chart_id': 'str',
        'enable_workflow': 'bool',
        'name': 'str',
        'remark': 'str',
        'account_list': 'list[object]',
        'name_field_list': 'list[object]',
        'department_list': 'list[object]',
        'enable_change_owner': 'bool',
        'module_name': 'str',
        'module_icon': 'str',
        'id': 'str',
        'company_id': 'str',
        'application_id': 'str',
        'create_time': 'float',
        'update_time': 'float',
        'create_account_id': 'str',
        'create_account_name': 'str',
        'update_account_id': 'str',
        'update_account_name': 'str',
        'app_name': 'str',
        'app_color': 'str',
        'app_icon': 'str',
        'is_delete': 'bool'
    }

    attribute_map = {
        'table_id': 'tableId',
        'chart_id': 'chartId',
        'enable_workflow': 'enableWorkflow',
        'name': 'name',
        'remark': 'remark',
        'account_list': 'accountList',
        'name_field_list': 'nameFieldList',
        'department_list': 'departmentList',
        'enable_change_owner': 'enableChangeOwner',
        'module_name': 'moduleName',
        'module_icon': 'moduleIcon',
        'id': 'id',
        'company_id': 'companyId',
        'application_id': 'applicationId',
        'create_time': 'createTime',
        'update_time': 'updateTime',
        'create_account_id': 'createAccountId',
        'create_account_name': 'createAccountName',
        'update_account_id': 'updateAccountId',
        'update_account_name': 'updateAccountName',
        'app_name': 'appName',
        'app_color': 'appColor',
        'app_icon': 'appIcon',
        'is_delete': 'isDelete'
    }

    def __init__(self, table_id=None, chart_id=None, enable_workflow=None, name=None, remark=None, account_list=None, name_field_list=None, department_list=None, enable_change_owner=None, module_name=None, module_icon=None, id=None, company_id=None, application_id=None, create_time=None, update_time=None, create_account_id=None, create_account_name=None, update_account_id=None, update_account_name=None, app_name=None, app_color=None, app_icon=None, is_delete=None):  # noqa: E501
        """TableWorkflowVO - a model defined in Swagger"""  # noqa: E501
        self._table_id = None
        self._chart_id = None
        self._enable_workflow = None
        self._name = None
        self._remark = None
        self._account_list = None
        self._name_field_list = None
        self._department_list = None
        self._enable_change_owner = None
        self._module_name = None
        self._module_icon = None
        self._id = None
        self._company_id = None
        self._application_id = None
        self._create_time = None
        self._update_time = None
        self._create_account_id = None
        self._create_account_name = None
        self._update_account_id = None
        self._update_account_name = None
        self._app_name = None
        self._app_color = None
        self._app_icon = None
        self._is_delete = None
        self.discriminator = None
        if table_id is not None:
            self.table_id = table_id
        if chart_id is not None:
            self.chart_id = chart_id
        if enable_workflow is not None:
            self.enable_workflow = enable_workflow
        if name is not None:
            self.name = name
        if remark is not None:
            self.remark = remark
        if account_list is not None:
            self.account_list = account_list
        if name_field_list is not None:
            self.name_field_list = name_field_list
        if department_list is not None:
            self.department_list = department_list
        if enable_change_owner is not None:
            self.enable_change_owner = enable_change_owner
        if module_name is not None:
            self.module_name = module_name
        if module_icon is not None:
            self.module_icon = module_icon
        if id is not None:
            self.id = id
        if company_id is not None:
            self.company_id = company_id
        if application_id is not None:
            self.application_id = application_id
        if create_time is not None:
            self.create_time = create_time
        if update_time is not None:
            self.update_time = update_time
        if create_account_id is not None:
            self.create_account_id = create_account_id
        if create_account_name is not None:
            self.create_account_name = create_account_name
        if update_account_id is not None:
            self.update_account_id = update_account_id
        if update_account_name is not None:
            self.update_account_name = update_account_name
        if app_name is not None:
            self.app_name = app_name
        if app_color is not None:
            self.app_color = app_color
        if app_icon is not None:
            self.app_icon = app_icon
        if is_delete is not None:
            self.is_delete = is_delete

    @property
    def table_id(self):
        """Gets the table_id of this TableWorkflowVO.  # noqa: E501

        数据表ID  # noqa: E501

        :return: The table_id of this TableWorkflowVO.  # noqa: E501
        :rtype: str
        """
        return self._table_id

    @table_id.setter
    def table_id(self, table_id):
        """Sets the table_id of this TableWorkflowVO.

        数据表ID  # noqa: E501

        :param table_id: The table_id of this TableWorkflowVO.  # noqa: E501
        :type: str
        """

        self._table_id = table_id

    @property
    def chart_id(self):
        """Gets the chart_id of this TableWorkflowVO.  # noqa: E501

        当前流程图  # noqa: E501

        :return: The chart_id of this TableWorkflowVO.  # noqa: E501
        :rtype: str
        """
        return self._chart_id

    @chart_id.setter
    def chart_id(self, chart_id):
        """Sets the chart_id of this TableWorkflowVO.

        当前流程图  # noqa: E501

        :param chart_id: The chart_id of this TableWorkflowVO.  # noqa: E501
        :type: str
        """

        self._chart_id = chart_id

    @property
    def enable_workflow(self):
        """Gets the enable_workflow of this TableWorkflowVO.  # noqa: E501

        是否启用  # noqa: E501

        :return: The enable_workflow of this TableWorkflowVO.  # noqa: E501
        :rtype: bool
        """
        return self._enable_workflow

    @enable_workflow.setter
    def enable_workflow(self, enable_workflow):
        """Sets the enable_workflow of this TableWorkflowVO.

        是否启用  # noqa: E501

        :param enable_workflow: The enable_workflow of this TableWorkflowVO.  # noqa: E501
        :type: bool
        """

        self._enable_workflow = enable_workflow

    @property
    def name(self):
        """Gets the name of this TableWorkflowVO.  # noqa: E501

        名称  # noqa: E501

        :return: The name of this TableWorkflowVO.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this TableWorkflowVO.

        名称  # noqa: E501

        :param name: The name of this TableWorkflowVO.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def remark(self):
        """Gets the remark of this TableWorkflowVO.  # noqa: E501

        描述  # noqa: E501

        :return: The remark of this TableWorkflowVO.  # noqa: E501
        :rtype: str
        """
        return self._remark

    @remark.setter
    def remark(self, remark):
        """Sets the remark of this TableWorkflowVO.

        描述  # noqa: E501

        :param remark: The remark of this TableWorkflowVO.  # noqa: E501
        :type: str
        """

        self._remark = remark

    @property
    def account_list(self):
        """Gets the account_list of this TableWorkflowVO.  # noqa: E501

        可发起流程的用户列表  # noqa: E501

        :return: The account_list of this TableWorkflowVO.  # noqa: E501
        :rtype: list[object]
        """
        return self._account_list

    @account_list.setter
    def account_list(self, account_list):
        """Sets the account_list of this TableWorkflowVO.

        可发起流程的用户列表  # noqa: E501

        :param account_list: The account_list of this TableWorkflowVO.  # noqa: E501
        :type: list[object]
        """

        self._account_list = account_list

    @property
    def name_field_list(self):
        """Gets the name_field_list of this TableWorkflowVO.  # noqa: E501

        流程名称字段列表  # noqa: E501

        :return: The name_field_list of this TableWorkflowVO.  # noqa: E501
        :rtype: list[object]
        """
        return self._name_field_list

    @name_field_list.setter
    def name_field_list(self, name_field_list):
        """Sets the name_field_list of this TableWorkflowVO.

        流程名称字段列表  # noqa: E501

        :param name_field_list: The name_field_list of this TableWorkflowVO.  # noqa: E501
        :type: list[object]
        """

        self._name_field_list = name_field_list

    @property
    def department_list(self):
        """Gets the department_list of this TableWorkflowVO.  # noqa: E501

        可发起流程的部门  # noqa: E501

        :return: The department_list of this TableWorkflowVO.  # noqa: E501
        :rtype: list[object]
        """
        return self._department_list

    @department_list.setter
    def department_list(self, department_list):
        """Sets the department_list of this TableWorkflowVO.

        可发起流程的部门  # noqa: E501

        :param department_list: The department_list of this TableWorkflowVO.  # noqa: E501
        :type: list[object]
        """

        self._department_list = department_list

    @property
    def enable_change_owner(self):
        """Gets the enable_change_owner of this TableWorkflowVO.  # noqa: E501

        是否允许在流程中调整审批人  # noqa: E501

        :return: The enable_change_owner of this TableWorkflowVO.  # noqa: E501
        :rtype: bool
        """
        return self._enable_change_owner

    @enable_change_owner.setter
    def enable_change_owner(self, enable_change_owner):
        """Sets the enable_change_owner of this TableWorkflowVO.

        是否允许在流程中调整审批人  # noqa: E501

        :param enable_change_owner: The enable_change_owner of this TableWorkflowVO.  # noqa: E501
        :type: bool
        """

        self._enable_change_owner = enable_change_owner

    @property
    def module_name(self):
        """Gets the module_name of this TableWorkflowVO.  # noqa: E501

        数据表名称  # noqa: E501

        :return: The module_name of this TableWorkflowVO.  # noqa: E501
        :rtype: str
        """
        return self._module_name

    @module_name.setter
    def module_name(self, module_name):
        """Sets the module_name of this TableWorkflowVO.

        数据表名称  # noqa: E501

        :param module_name: The module_name of this TableWorkflowVO.  # noqa: E501
        :type: str
        """

        self._module_name = module_name

    @property
    def module_icon(self):
        """Gets the module_icon of this TableWorkflowVO.  # noqa: E501

        数据表图标  # noqa: E501

        :return: The module_icon of this TableWorkflowVO.  # noqa: E501
        :rtype: str
        """
        return self._module_icon

    @module_icon.setter
    def module_icon(self, module_icon):
        """Sets the module_icon of this TableWorkflowVO.

        数据表图标  # noqa: E501

        :param module_icon: The module_icon of this TableWorkflowVO.  # noqa: E501
        :type: str
        """

        self._module_icon = module_icon

    @property
    def id(self):
        """Gets the id of this TableWorkflowVO.  # noqa: E501

        ID  # noqa: E501

        :return: The id of this TableWorkflowVO.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this TableWorkflowVO.

        ID  # noqa: E501

        :param id: The id of this TableWorkflowVO.  # noqa: E501
        :type: str
        """

        self._id = id

    @property
    def company_id(self):
        """Gets the company_id of this TableWorkflowVO.  # noqa: E501

        团队ID  # noqa: E501

        :return: The company_id of this TableWorkflowVO.  # noqa: E501
        :rtype: str
        """
        return self._company_id

    @company_id.setter
    def company_id(self, company_id):
        """Sets the company_id of this TableWorkflowVO.

        团队ID  # noqa: E501

        :param company_id: The company_id of this TableWorkflowVO.  # noqa: E501
        :type: str
        """

        self._company_id = company_id

    @property
    def application_id(self):
        """Gets the application_id of this TableWorkflowVO.  # noqa: E501

        应用ID  # noqa: E501

        :return: The application_id of this TableWorkflowVO.  # noqa: E501
        :rtype: str
        """
        return self._application_id

    @application_id.setter
    def application_id(self, application_id):
        """Sets the application_id of this TableWorkflowVO.

        应用ID  # noqa: E501

        :param application_id: The application_id of this TableWorkflowVO.  # noqa: E501
        :type: str
        """

        self._application_id = application_id

    @property
    def create_time(self):
        """Gets the create_time of this TableWorkflowVO.  # noqa: E501

        创建时间  # noqa: E501

        :return: The create_time of this TableWorkflowVO.  # noqa: E501
        :rtype: float
        """
        return self._create_time

    @create_time.setter
    def create_time(self, create_time):
        """Sets the create_time of this TableWorkflowVO.

        创建时间  # noqa: E501

        :param create_time: The create_time of this TableWorkflowVO.  # noqa: E501
        :type: float
        """

        self._create_time = create_time

    @property
    def update_time(self):
        """Gets the update_time of this TableWorkflowVO.  # noqa: E501

        最后更新时间  # noqa: E501

        :return: The update_time of this TableWorkflowVO.  # noqa: E501
        :rtype: float
        """
        return self._update_time

    @update_time.setter
    def update_time(self, update_time):
        """Sets the update_time of this TableWorkflowVO.

        最后更新时间  # noqa: E501

        :param update_time: The update_time of this TableWorkflowVO.  # noqa: E501
        :type: float
        """

        self._update_time = update_time

    @property
    def create_account_id(self):
        """Gets the create_account_id of this TableWorkflowVO.  # noqa: E501

        创建人ID  # noqa: E501

        :return: The create_account_id of this TableWorkflowVO.  # noqa: E501
        :rtype: str
        """
        return self._create_account_id

    @create_account_id.setter
    def create_account_id(self, create_account_id):
        """Sets the create_account_id of this TableWorkflowVO.

        创建人ID  # noqa: E501

        :param create_account_id: The create_account_id of this TableWorkflowVO.  # noqa: E501
        :type: str
        """

        self._create_account_id = create_account_id

    @property
    def create_account_name(self):
        """Gets the create_account_name of this TableWorkflowVO.  # noqa: E501

        创建人名称  # noqa: E501

        :return: The create_account_name of this TableWorkflowVO.  # noqa: E501
        :rtype: str
        """
        return self._create_account_name

    @create_account_name.setter
    def create_account_name(self, create_account_name):
        """Sets the create_account_name of this TableWorkflowVO.

        创建人名称  # noqa: E501

        :param create_account_name: The create_account_name of this TableWorkflowVO.  # noqa: E501
        :type: str
        """

        self._create_account_name = create_account_name

    @property
    def update_account_id(self):
        """Gets the update_account_id of this TableWorkflowVO.  # noqa: E501

        最后更新人ID  # noqa: E501

        :return: The update_account_id of this TableWorkflowVO.  # noqa: E501
        :rtype: str
        """
        return self._update_account_id

    @update_account_id.setter
    def update_account_id(self, update_account_id):
        """Sets the update_account_id of this TableWorkflowVO.

        最后更新人ID  # noqa: E501

        :param update_account_id: The update_account_id of this TableWorkflowVO.  # noqa: E501
        :type: str
        """

        self._update_account_id = update_account_id

    @property
    def update_account_name(self):
        """Gets the update_account_name of this TableWorkflowVO.  # noqa: E501

        最后更新人名称  # noqa: E501

        :return: The update_account_name of this TableWorkflowVO.  # noqa: E501
        :rtype: str
        """
        return self._update_account_name

    @update_account_name.setter
    def update_account_name(self, update_account_name):
        """Sets the update_account_name of this TableWorkflowVO.

        最后更新人名称  # noqa: E501

        :param update_account_name: The update_account_name of this TableWorkflowVO.  # noqa: E501
        :type: str
        """

        self._update_account_name = update_account_name

    @property
    def app_name(self):
        """Gets the app_name of this TableWorkflowVO.  # noqa: E501

        应用名称  # noqa: E501

        :return: The app_name of this TableWorkflowVO.  # noqa: E501
        :rtype: str
        """
        return self._app_name

    @app_name.setter
    def app_name(self, app_name):
        """Sets the app_name of this TableWorkflowVO.

        应用名称  # noqa: E501

        :param app_name: The app_name of this TableWorkflowVO.  # noqa: E501
        :type: str
        """

        self._app_name = app_name

    @property
    def app_color(self):
        """Gets the app_color of this TableWorkflowVO.  # noqa: E501

        应用颜色  # noqa: E501

        :return: The app_color of this TableWorkflowVO.  # noqa: E501
        :rtype: str
        """
        return self._app_color

    @app_color.setter
    def app_color(self, app_color):
        """Sets the app_color of this TableWorkflowVO.

        应用颜色  # noqa: E501

        :param app_color: The app_color of this TableWorkflowVO.  # noqa: E501
        :type: str
        """

        self._app_color = app_color

    @property
    def app_icon(self):
        """Gets the app_icon of this TableWorkflowVO.  # noqa: E501

        应用图标  # noqa: E501

        :return: The app_icon of this TableWorkflowVO.  # noqa: E501
        :rtype: str
        """
        return self._app_icon

    @app_icon.setter
    def app_icon(self, app_icon):
        """Sets the app_icon of this TableWorkflowVO.

        应用图标  # noqa: E501

        :param app_icon: The app_icon of this TableWorkflowVO.  # noqa: E501
        :type: str
        """

        self._app_icon = app_icon

    @property
    def is_delete(self):
        """Gets the is_delete of this TableWorkflowVO.  # noqa: E501

        是否已删除  # noqa: E501

        :return: The is_delete of this TableWorkflowVO.  # noqa: E501
        :rtype: bool
        """
        return self._is_delete

    @is_delete.setter
    def is_delete(self, is_delete):
        """Sets the is_delete of this TableWorkflowVO.

        是否已删除  # noqa: E501

        :param is_delete: The is_delete of this TableWorkflowVO.  # noqa: E501
        :type: bool
        """

        self._is_delete = is_delete

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(TableWorkflowVO, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, TableWorkflowVO):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
