# coding: utf-8

"""
    织信开放API接口

    织信开放API接口  # noqa: E501

    OpenAPI spec version: v2
    Contact: sales@conrerstone365.cn
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class TableWorkflowInstanceNodeVO(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'table_id': 'str',
        'workflow_id': 'str',
        'instance_id': 'str',
        'before_node_id': 'str',
        'before_node_name': 'str',
        'before_node_color': 'str',
        'node_id': 'str',
        'node_name': 'str',
        'node_color': 'str',
        'node_type': 'str',
        'enter_time': 'float',
        'leave_time': 'float',
        'opt_account_id': 'str',
        'status': 'str',
        'name': 'str',
        'owner_account_list': 'list[TableAccountSimple]',
        'cc_account_list': 'list[TableAccountSimple]',
        'agree_count': 'int',
        'wait_count': 'int',
        'form_data': 'dict(str, object)',
        'transfer': 'list[TableWorkflowInstanceNodeTransfer]',
        'opt_account_id_avatar': 'str',
        'opt_account_id_name': 'str',
        'id': 'str',
        'company_id': 'str',
        'application_id': 'str',
        'create_time': 'float',
        'update_time': 'float',
        'create_account_id': 'str',
        'create_account_name': 'str',
        'update_account_id': 'str',
        'update_account_name': 'str',
        'app_name': 'str',
        'app_color': 'str',
        'app_icon': 'str',
        'is_delete': 'bool'
    }

    attribute_map = {
        'table_id': 'tableId',
        'workflow_id': 'workflowId',
        'instance_id': 'instanceId',
        'before_node_id': 'beforeNodeId',
        'before_node_name': 'beforeNodeName',
        'before_node_color': 'beforeNodeColor',
        'node_id': 'nodeId',
        'node_name': 'nodeName',
        'node_color': 'nodeColor',
        'node_type': 'nodeType',
        'enter_time': 'enterTime',
        'leave_time': 'leaveTime',
        'opt_account_id': 'optAccountId',
        'status': 'status',
        'name': 'name',
        'owner_account_list': 'ownerAccountList',
        'cc_account_list': 'ccAccountList',
        'agree_count': 'agreeCount',
        'wait_count': 'waitCount',
        'form_data': 'formData',
        'transfer': 'transfer',
        'opt_account_id_avatar': 'optAccountIdAvatar',
        'opt_account_id_name': 'optAccountIdName',
        'id': 'id',
        'company_id': 'companyId',
        'application_id': 'applicationId',
        'create_time': 'createTime',
        'update_time': 'updateTime',
        'create_account_id': 'createAccountId',
        'create_account_name': 'createAccountName',
        'update_account_id': 'updateAccountId',
        'update_account_name': 'updateAccountName',
        'app_name': 'appName',
        'app_color': 'appColor',
        'app_icon': 'appIcon',
        'is_delete': 'isDelete'
    }

    def __init__(self, table_id=None, workflow_id=None, instance_id=None, before_node_id=None, before_node_name=None, before_node_color=None, node_id=None, node_name=None, node_color=None, node_type=None, enter_time=None, leave_time=None, opt_account_id=None, status=None, name=None, owner_account_list=None, cc_account_list=None, agree_count=None, wait_count=None, form_data=None, transfer=None, opt_account_id_avatar=None, opt_account_id_name=None, id=None, company_id=None, application_id=None, create_time=None, update_time=None, create_account_id=None, create_account_name=None, update_account_id=None, update_account_name=None, app_name=None, app_color=None, app_icon=None, is_delete=None):  # noqa: E501
        """TableWorkflowInstanceNodeVO - a model defined in Swagger"""  # noqa: E501
        self._table_id = None
        self._workflow_id = None
        self._instance_id = None
        self._before_node_id = None
        self._before_node_name = None
        self._before_node_color = None
        self._node_id = None
        self._node_name = None
        self._node_color = None
        self._node_type = None
        self._enter_time = None
        self._leave_time = None
        self._opt_account_id = None
        self._status = None
        self._name = None
        self._owner_account_list = None
        self._cc_account_list = None
        self._agree_count = None
        self._wait_count = None
        self._form_data = None
        self._transfer = None
        self._opt_account_id_avatar = None
        self._opt_account_id_name = None
        self._id = None
        self._company_id = None
        self._application_id = None
        self._create_time = None
        self._update_time = None
        self._create_account_id = None
        self._create_account_name = None
        self._update_account_id = None
        self._update_account_name = None
        self._app_name = None
        self._app_color = None
        self._app_icon = None
        self._is_delete = None
        self.discriminator = None
        if table_id is not None:
            self.table_id = table_id
        if workflow_id is not None:
            self.workflow_id = workflow_id
        if instance_id is not None:
            self.instance_id = instance_id
        if before_node_id is not None:
            self.before_node_id = before_node_id
        if before_node_name is not None:
            self.before_node_name = before_node_name
        if before_node_color is not None:
            self.before_node_color = before_node_color
        if node_id is not None:
            self.node_id = node_id
        if node_name is not None:
            self.node_name = node_name
        if node_color is not None:
            self.node_color = node_color
        if node_type is not None:
            self.node_type = node_type
        if enter_time is not None:
            self.enter_time = enter_time
        if leave_time is not None:
            self.leave_time = leave_time
        if opt_account_id is not None:
            self.opt_account_id = opt_account_id
        if status is not None:
            self.status = status
        if name is not None:
            self.name = name
        if owner_account_list is not None:
            self.owner_account_list = owner_account_list
        if cc_account_list is not None:
            self.cc_account_list = cc_account_list
        if agree_count is not None:
            self.agree_count = agree_count
        if wait_count is not None:
            self.wait_count = wait_count
        if form_data is not None:
            self.form_data = form_data
        if transfer is not None:
            self.transfer = transfer
        if opt_account_id_avatar is not None:
            self.opt_account_id_avatar = opt_account_id_avatar
        if opt_account_id_name is not None:
            self.opt_account_id_name = opt_account_id_name
        if id is not None:
            self.id = id
        if company_id is not None:
            self.company_id = company_id
        if application_id is not None:
            self.application_id = application_id
        if create_time is not None:
            self.create_time = create_time
        if update_time is not None:
            self.update_time = update_time
        if create_account_id is not None:
            self.create_account_id = create_account_id
        if create_account_name is not None:
            self.create_account_name = create_account_name
        if update_account_id is not None:
            self.update_account_id = update_account_id
        if update_account_name is not None:
            self.update_account_name = update_account_name
        if app_name is not None:
            self.app_name = app_name
        if app_color is not None:
            self.app_color = app_color
        if app_icon is not None:
            self.app_icon = app_icon
        if is_delete is not None:
            self.is_delete = is_delete

    @property
    def table_id(self):
        """Gets the table_id of this TableWorkflowInstanceNodeVO.  # noqa: E501

        数据表  # noqa: E501

        :return: The table_id of this TableWorkflowInstanceNodeVO.  # noqa: E501
        :rtype: str
        """
        return self._table_id

    @table_id.setter
    def table_id(self, table_id):
        """Sets the table_id of this TableWorkflowInstanceNodeVO.

        数据表  # noqa: E501

        :param table_id: The table_id of this TableWorkflowInstanceNodeVO.  # noqa: E501
        :type: str
        """

        self._table_id = table_id

    @property
    def workflow_id(self):
        """Gets the workflow_id of this TableWorkflowInstanceNodeVO.  # noqa: E501

        流程定义  # noqa: E501

        :return: The workflow_id of this TableWorkflowInstanceNodeVO.  # noqa: E501
        :rtype: str
        """
        return self._workflow_id

    @workflow_id.setter
    def workflow_id(self, workflow_id):
        """Sets the workflow_id of this TableWorkflowInstanceNodeVO.

        流程定义  # noqa: E501

        :param workflow_id: The workflow_id of this TableWorkflowInstanceNodeVO.  # noqa: E501
        :type: str
        """

        self._workflow_id = workflow_id

    @property
    def instance_id(self):
        """Gets the instance_id of this TableWorkflowInstanceNodeVO.  # noqa: E501

        流程实例  # noqa: E501

        :return: The instance_id of this TableWorkflowInstanceNodeVO.  # noqa: E501
        :rtype: str
        """
        return self._instance_id

    @instance_id.setter
    def instance_id(self, instance_id):
        """Sets the instance_id of this TableWorkflowInstanceNodeVO.

        流程实例  # noqa: E501

        :param instance_id: The instance_id of this TableWorkflowInstanceNodeVO.  # noqa: E501
        :type: str
        """

        self._instance_id = instance_id

    @property
    def before_node_id(self):
        """Gets the before_node_id of this TableWorkflowInstanceNodeVO.  # noqa: E501

        上一个节点ID  # noqa: E501

        :return: The before_node_id of this TableWorkflowInstanceNodeVO.  # noqa: E501
        :rtype: str
        """
        return self._before_node_id

    @before_node_id.setter
    def before_node_id(self, before_node_id):
        """Sets the before_node_id of this TableWorkflowInstanceNodeVO.

        上一个节点ID  # noqa: E501

        :param before_node_id: The before_node_id of this TableWorkflowInstanceNodeVO.  # noqa: E501
        :type: str
        """

        self._before_node_id = before_node_id

    @property
    def before_node_name(self):
        """Gets the before_node_name of this TableWorkflowInstanceNodeVO.  # noqa: E501

        上一个节点名称  # noqa: E501

        :return: The before_node_name of this TableWorkflowInstanceNodeVO.  # noqa: E501
        :rtype: str
        """
        return self._before_node_name

    @before_node_name.setter
    def before_node_name(self, before_node_name):
        """Sets the before_node_name of this TableWorkflowInstanceNodeVO.

        上一个节点名称  # noqa: E501

        :param before_node_name: The before_node_name of this TableWorkflowInstanceNodeVO.  # noqa: E501
        :type: str
        """

        self._before_node_name = before_node_name

    @property
    def before_node_color(self):
        """Gets the before_node_color of this TableWorkflowInstanceNodeVO.  # noqa: E501

        上一个节点颜色  # noqa: E501

        :return: The before_node_color of this TableWorkflowInstanceNodeVO.  # noqa: E501
        :rtype: str
        """
        return self._before_node_color

    @before_node_color.setter
    def before_node_color(self, before_node_color):
        """Sets the before_node_color of this TableWorkflowInstanceNodeVO.

        上一个节点颜色  # noqa: E501

        :param before_node_color: The before_node_color of this TableWorkflowInstanceNodeVO.  # noqa: E501
        :type: str
        """

        self._before_node_color = before_node_color

    @property
    def node_id(self):
        """Gets the node_id of this TableWorkflowInstanceNodeVO.  # noqa: E501

        节点ID  # noqa: E501

        :return: The node_id of this TableWorkflowInstanceNodeVO.  # noqa: E501
        :rtype: str
        """
        return self._node_id

    @node_id.setter
    def node_id(self, node_id):
        """Sets the node_id of this TableWorkflowInstanceNodeVO.

        节点ID  # noqa: E501

        :param node_id: The node_id of this TableWorkflowInstanceNodeVO.  # noqa: E501
        :type: str
        """

        self._node_id = node_id

    @property
    def node_name(self):
        """Gets the node_name of this TableWorkflowInstanceNodeVO.  # noqa: E501

        节点名称  # noqa: E501

        :return: The node_name of this TableWorkflowInstanceNodeVO.  # noqa: E501
        :rtype: str
        """
        return self._node_name

    @node_name.setter
    def node_name(self, node_name):
        """Sets the node_name of this TableWorkflowInstanceNodeVO.

        节点名称  # noqa: E501

        :param node_name: The node_name of this TableWorkflowInstanceNodeVO.  # noqa: E501
        :type: str
        """

        self._node_name = node_name

    @property
    def node_color(self):
        """Gets the node_color of this TableWorkflowInstanceNodeVO.  # noqa: E501

        节点颜色  # noqa: E501

        :return: The node_color of this TableWorkflowInstanceNodeVO.  # noqa: E501
        :rtype: str
        """
        return self._node_color

    @node_color.setter
    def node_color(self, node_color):
        """Sets the node_color of this TableWorkflowInstanceNodeVO.

        节点颜色  # noqa: E501

        :param node_color: The node_color of this TableWorkflowInstanceNodeVO.  # noqa: E501
        :type: str
        """

        self._node_color = node_color

    @property
    def node_type(self):
        """Gets the node_type of this TableWorkflowInstanceNodeVO.  # noqa: E501

        节点类型  # noqa: E501

        :return: The node_type of this TableWorkflowInstanceNodeVO.  # noqa: E501
        :rtype: str
        """
        return self._node_type

    @node_type.setter
    def node_type(self, node_type):
        """Sets the node_type of this TableWorkflowInstanceNodeVO.

        节点类型  # noqa: E501

        :param node_type: The node_type of this TableWorkflowInstanceNodeVO.  # noqa: E501
        :type: str
        """
        allowed_values = ["Start", "End", "Event", "Fork", "Join"]  # noqa: E501
        if node_type not in allowed_values:
            raise ValueError(
                "Invalid value for `node_type` ({0}), must be one of {1}"  # noqa: E501
                .format(node_type, allowed_values)
            )

        self._node_type = node_type

    @property
    def enter_time(self):
        """Gets the enter_time of this TableWorkflowInstanceNodeVO.  # noqa: E501

        进入时间  # noqa: E501

        :return: The enter_time of this TableWorkflowInstanceNodeVO.  # noqa: E501
        :rtype: float
        """
        return self._enter_time

    @enter_time.setter
    def enter_time(self, enter_time):
        """Sets the enter_time of this TableWorkflowInstanceNodeVO.

        进入时间  # noqa: E501

        :param enter_time: The enter_time of this TableWorkflowInstanceNodeVO.  # noqa: E501
        :type: float
        """

        self._enter_time = enter_time

    @property
    def leave_time(self):
        """Gets the leave_time of this TableWorkflowInstanceNodeVO.  # noqa: E501

        离开时间  # noqa: E501

        :return: The leave_time of this TableWorkflowInstanceNodeVO.  # noqa: E501
        :rtype: float
        """
        return self._leave_time

    @leave_time.setter
    def leave_time(self, leave_time):
        """Sets the leave_time of this TableWorkflowInstanceNodeVO.

        离开时间  # noqa: E501

        :param leave_time: The leave_time of this TableWorkflowInstanceNodeVO.  # noqa: E501
        :type: float
        """

        self._leave_time = leave_time

    @property
    def opt_account_id(self):
        """Gets the opt_account_id of this TableWorkflowInstanceNodeVO.  # noqa: E501

        操作人  # noqa: E501

        :return: The opt_account_id of this TableWorkflowInstanceNodeVO.  # noqa: E501
        :rtype: str
        """
        return self._opt_account_id

    @opt_account_id.setter
    def opt_account_id(self, opt_account_id):
        """Sets the opt_account_id of this TableWorkflowInstanceNodeVO.

        操作人  # noqa: E501

        :param opt_account_id: The opt_account_id of this TableWorkflowInstanceNodeVO.  # noqa: E501
        :type: str
        """

        self._opt_account_id = opt_account_id

    @property
    def status(self):
        """Gets the status of this TableWorkflowInstanceNodeVO.  # noqa: E501

        审批结果  # noqa: E501

        :return: The status of this TableWorkflowInstanceNodeVO.  # noqa: E501
        :rtype: str
        """
        return self._status

    @status.setter
    def status(self, status):
        """Sets the status of this TableWorkflowInstanceNodeVO.

        审批结果  # noqa: E501

        :param status: The status of this TableWorkflowInstanceNodeVO.  # noqa: E501
        :type: str
        """
        allowed_values = ["Agree", "Refuse", "Rollback"]  # noqa: E501
        if status not in allowed_values:
            raise ValueError(
                "Invalid value for `status` ({0}), must be one of {1}"  # noqa: E501
                .format(status, allowed_values)
            )

        self._status = status

    @property
    def name(self):
        """Gets the name of this TableWorkflowInstanceNodeVO.  # noqa: E501

        审批意见  # noqa: E501

        :return: The name of this TableWorkflowInstanceNodeVO.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this TableWorkflowInstanceNodeVO.

        审批意见  # noqa: E501

        :param name: The name of this TableWorkflowInstanceNodeVO.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def owner_account_list(self):
        """Gets the owner_account_list of this TableWorkflowInstanceNodeVO.  # noqa: E501

        责任人  # noqa: E501

        :return: The owner_account_list of this TableWorkflowInstanceNodeVO.  # noqa: E501
        :rtype: list[TableAccountSimple]
        """
        return self._owner_account_list

    @owner_account_list.setter
    def owner_account_list(self, owner_account_list):
        """Sets the owner_account_list of this TableWorkflowInstanceNodeVO.

        责任人  # noqa: E501

        :param owner_account_list: The owner_account_list of this TableWorkflowInstanceNodeVO.  # noqa: E501
        :type: list[TableAccountSimple]
        """

        self._owner_account_list = owner_account_list

    @property
    def cc_account_list(self):
        """Gets the cc_account_list of this TableWorkflowInstanceNodeVO.  # noqa: E501

        抄送人  # noqa: E501

        :return: The cc_account_list of this TableWorkflowInstanceNodeVO.  # noqa: E501
        :rtype: list[TableAccountSimple]
        """
        return self._cc_account_list

    @cc_account_list.setter
    def cc_account_list(self, cc_account_list):
        """Sets the cc_account_list of this TableWorkflowInstanceNodeVO.

        抄送人  # noqa: E501

        :param cc_account_list: The cc_account_list of this TableWorkflowInstanceNodeVO.  # noqa: E501
        :type: list[TableAccountSimple]
        """

        self._cc_account_list = cc_account_list

    @property
    def agree_count(self):
        """Gets the agree_count of this TableWorkflowInstanceNodeVO.  # noqa: E501

        同意数量  # noqa: E501

        :return: The agree_count of this TableWorkflowInstanceNodeVO.  # noqa: E501
        :rtype: int
        """
        return self._agree_count

    @agree_count.setter
    def agree_count(self, agree_count):
        """Sets the agree_count of this TableWorkflowInstanceNodeVO.

        同意数量  # noqa: E501

        :param agree_count: The agree_count of this TableWorkflowInstanceNodeVO.  # noqa: E501
        :type: int
        """

        self._agree_count = agree_count

    @property
    def wait_count(self):
        """Gets the wait_count of this TableWorkflowInstanceNodeVO.  # noqa: E501

        等待数量  # noqa: E501

        :return: The wait_count of this TableWorkflowInstanceNodeVO.  # noqa: E501
        :rtype: int
        """
        return self._wait_count

    @wait_count.setter
    def wait_count(self, wait_count):
        """Sets the wait_count of this TableWorkflowInstanceNodeVO.

        等待数量  # noqa: E501

        :param wait_count: The wait_count of this TableWorkflowInstanceNodeVO.  # noqa: E501
        :type: int
        """

        self._wait_count = wait_count

    @property
    def form_data(self):
        """Gets the form_data of this TableWorkflowInstanceNodeVO.  # noqa: E501

        表单数据  # noqa: E501

        :return: The form_data of this TableWorkflowInstanceNodeVO.  # noqa: E501
        :rtype: dict(str, object)
        """
        return self._form_data

    @form_data.setter
    def form_data(self, form_data):
        """Sets the form_data of this TableWorkflowInstanceNodeVO.

        表单数据  # noqa: E501

        :param form_data: The form_data of this TableWorkflowInstanceNodeVO.  # noqa: E501
        :type: dict(str, object)
        """

        self._form_data = form_data

    @property
    def transfer(self):
        """Gets the transfer of this TableWorkflowInstanceNodeVO.  # noqa: E501

        转交信息  # noqa: E501

        :return: The transfer of this TableWorkflowInstanceNodeVO.  # noqa: E501
        :rtype: list[TableWorkflowInstanceNodeTransfer]
        """
        return self._transfer

    @transfer.setter
    def transfer(self, transfer):
        """Sets the transfer of this TableWorkflowInstanceNodeVO.

        转交信息  # noqa: E501

        :param transfer: The transfer of this TableWorkflowInstanceNodeVO.  # noqa: E501
        :type: list[TableWorkflowInstanceNodeTransfer]
        """

        self._transfer = transfer

    @property
    def opt_account_id_avatar(self):
        """Gets the opt_account_id_avatar of this TableWorkflowInstanceNodeVO.  # noqa: E501

        操作人图标  # noqa: E501

        :return: The opt_account_id_avatar of this TableWorkflowInstanceNodeVO.  # noqa: E501
        :rtype: str
        """
        return self._opt_account_id_avatar

    @opt_account_id_avatar.setter
    def opt_account_id_avatar(self, opt_account_id_avatar):
        """Sets the opt_account_id_avatar of this TableWorkflowInstanceNodeVO.

        操作人图标  # noqa: E501

        :param opt_account_id_avatar: The opt_account_id_avatar of this TableWorkflowInstanceNodeVO.  # noqa: E501
        :type: str
        """

        self._opt_account_id_avatar = opt_account_id_avatar

    @property
    def opt_account_id_name(self):
        """Gets the opt_account_id_name of this TableWorkflowInstanceNodeVO.  # noqa: E501

        操作人名称  # noqa: E501

        :return: The opt_account_id_name of this TableWorkflowInstanceNodeVO.  # noqa: E501
        :rtype: str
        """
        return self._opt_account_id_name

    @opt_account_id_name.setter
    def opt_account_id_name(self, opt_account_id_name):
        """Sets the opt_account_id_name of this TableWorkflowInstanceNodeVO.

        操作人名称  # noqa: E501

        :param opt_account_id_name: The opt_account_id_name of this TableWorkflowInstanceNodeVO.  # noqa: E501
        :type: str
        """

        self._opt_account_id_name = opt_account_id_name

    @property
    def id(self):
        """Gets the id of this TableWorkflowInstanceNodeVO.  # noqa: E501

        ID  # noqa: E501

        :return: The id of this TableWorkflowInstanceNodeVO.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this TableWorkflowInstanceNodeVO.

        ID  # noqa: E501

        :param id: The id of this TableWorkflowInstanceNodeVO.  # noqa: E501
        :type: str
        """

        self._id = id

    @property
    def company_id(self):
        """Gets the company_id of this TableWorkflowInstanceNodeVO.  # noqa: E501

        团队ID  # noqa: E501

        :return: The company_id of this TableWorkflowInstanceNodeVO.  # noqa: E501
        :rtype: str
        """
        return self._company_id

    @company_id.setter
    def company_id(self, company_id):
        """Sets the company_id of this TableWorkflowInstanceNodeVO.

        团队ID  # noqa: E501

        :param company_id: The company_id of this TableWorkflowInstanceNodeVO.  # noqa: E501
        :type: str
        """

        self._company_id = company_id

    @property
    def application_id(self):
        """Gets the application_id of this TableWorkflowInstanceNodeVO.  # noqa: E501

        应用ID  # noqa: E501

        :return: The application_id of this TableWorkflowInstanceNodeVO.  # noqa: E501
        :rtype: str
        """
        return self._application_id

    @application_id.setter
    def application_id(self, application_id):
        """Sets the application_id of this TableWorkflowInstanceNodeVO.

        应用ID  # noqa: E501

        :param application_id: The application_id of this TableWorkflowInstanceNodeVO.  # noqa: E501
        :type: str
        """

        self._application_id = application_id

    @property
    def create_time(self):
        """Gets the create_time of this TableWorkflowInstanceNodeVO.  # noqa: E501

        创建时间  # noqa: E501

        :return: The create_time of this TableWorkflowInstanceNodeVO.  # noqa: E501
        :rtype: float
        """
        return self._create_time

    @create_time.setter
    def create_time(self, create_time):
        """Sets the create_time of this TableWorkflowInstanceNodeVO.

        创建时间  # noqa: E501

        :param create_time: The create_time of this TableWorkflowInstanceNodeVO.  # noqa: E501
        :type: float
        """

        self._create_time = create_time

    @property
    def update_time(self):
        """Gets the update_time of this TableWorkflowInstanceNodeVO.  # noqa: E501

        最后更新时间  # noqa: E501

        :return: The update_time of this TableWorkflowInstanceNodeVO.  # noqa: E501
        :rtype: float
        """
        return self._update_time

    @update_time.setter
    def update_time(self, update_time):
        """Sets the update_time of this TableWorkflowInstanceNodeVO.

        最后更新时间  # noqa: E501

        :param update_time: The update_time of this TableWorkflowInstanceNodeVO.  # noqa: E501
        :type: float
        """

        self._update_time = update_time

    @property
    def create_account_id(self):
        """Gets the create_account_id of this TableWorkflowInstanceNodeVO.  # noqa: E501

        创建人ID  # noqa: E501

        :return: The create_account_id of this TableWorkflowInstanceNodeVO.  # noqa: E501
        :rtype: str
        """
        return self._create_account_id

    @create_account_id.setter
    def create_account_id(self, create_account_id):
        """Sets the create_account_id of this TableWorkflowInstanceNodeVO.

        创建人ID  # noqa: E501

        :param create_account_id: The create_account_id of this TableWorkflowInstanceNodeVO.  # noqa: E501
        :type: str
        """

        self._create_account_id = create_account_id

    @property
    def create_account_name(self):
        """Gets the create_account_name of this TableWorkflowInstanceNodeVO.  # noqa: E501

        创建人名称  # noqa: E501

        :return: The create_account_name of this TableWorkflowInstanceNodeVO.  # noqa: E501
        :rtype: str
        """
        return self._create_account_name

    @create_account_name.setter
    def create_account_name(self, create_account_name):
        """Sets the create_account_name of this TableWorkflowInstanceNodeVO.

        创建人名称  # noqa: E501

        :param create_account_name: The create_account_name of this TableWorkflowInstanceNodeVO.  # noqa: E501
        :type: str
        """

        self._create_account_name = create_account_name

    @property
    def update_account_id(self):
        """Gets the update_account_id of this TableWorkflowInstanceNodeVO.  # noqa: E501

        最后更新人ID  # noqa: E501

        :return: The update_account_id of this TableWorkflowInstanceNodeVO.  # noqa: E501
        :rtype: str
        """
        return self._update_account_id

    @update_account_id.setter
    def update_account_id(self, update_account_id):
        """Sets the update_account_id of this TableWorkflowInstanceNodeVO.

        最后更新人ID  # noqa: E501

        :param update_account_id: The update_account_id of this TableWorkflowInstanceNodeVO.  # noqa: E501
        :type: str
        """

        self._update_account_id = update_account_id

    @property
    def update_account_name(self):
        """Gets the update_account_name of this TableWorkflowInstanceNodeVO.  # noqa: E501

        最后更新人名称  # noqa: E501

        :return: The update_account_name of this TableWorkflowInstanceNodeVO.  # noqa: E501
        :rtype: str
        """
        return self._update_account_name

    @update_account_name.setter
    def update_account_name(self, update_account_name):
        """Sets the update_account_name of this TableWorkflowInstanceNodeVO.

        最后更新人名称  # noqa: E501

        :param update_account_name: The update_account_name of this TableWorkflowInstanceNodeVO.  # noqa: E501
        :type: str
        """

        self._update_account_name = update_account_name

    @property
    def app_name(self):
        """Gets the app_name of this TableWorkflowInstanceNodeVO.  # noqa: E501

        应用名称  # noqa: E501

        :return: The app_name of this TableWorkflowInstanceNodeVO.  # noqa: E501
        :rtype: str
        """
        return self._app_name

    @app_name.setter
    def app_name(self, app_name):
        """Sets the app_name of this TableWorkflowInstanceNodeVO.

        应用名称  # noqa: E501

        :param app_name: The app_name of this TableWorkflowInstanceNodeVO.  # noqa: E501
        :type: str
        """

        self._app_name = app_name

    @property
    def app_color(self):
        """Gets the app_color of this TableWorkflowInstanceNodeVO.  # noqa: E501

        应用颜色  # noqa: E501

        :return: The app_color of this TableWorkflowInstanceNodeVO.  # noqa: E501
        :rtype: str
        """
        return self._app_color

    @app_color.setter
    def app_color(self, app_color):
        """Sets the app_color of this TableWorkflowInstanceNodeVO.

        应用颜色  # noqa: E501

        :param app_color: The app_color of this TableWorkflowInstanceNodeVO.  # noqa: E501
        :type: str
        """

        self._app_color = app_color

    @property
    def app_icon(self):
        """Gets the app_icon of this TableWorkflowInstanceNodeVO.  # noqa: E501

        应用图标  # noqa: E501

        :return: The app_icon of this TableWorkflowInstanceNodeVO.  # noqa: E501
        :rtype: str
        """
        return self._app_icon

    @app_icon.setter
    def app_icon(self, app_icon):
        """Sets the app_icon of this TableWorkflowInstanceNodeVO.

        应用图标  # noqa: E501

        :param app_icon: The app_icon of this TableWorkflowInstanceNodeVO.  # noqa: E501
        :type: str
        """

        self._app_icon = app_icon

    @property
    def is_delete(self):
        """Gets the is_delete of this TableWorkflowInstanceNodeVO.  # noqa: E501

        是否已删除  # noqa: E501

        :return: The is_delete of this TableWorkflowInstanceNodeVO.  # noqa: E501
        :rtype: bool
        """
        return self._is_delete

    @is_delete.setter
    def is_delete(self, is_delete):
        """Sets the is_delete of this TableWorkflowInstanceNodeVO.

        是否已删除  # noqa: E501

        :param is_delete: The is_delete of this TableWorkflowInstanceNodeVO.  # noqa: E501
        :type: bool
        """

        self._is_delete = is_delete

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(TableWorkflowInstanceNodeVO, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, TableWorkflowInstanceNodeVO):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
