# coding: utf-8

"""
    织信开放API接口

    织信开放API接口  # noqa: E501

    OpenAPI spec version: v2
    Contact: sales@conrerstone365.cn
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class TableVO(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'module_name': 'str',
        'module_icon': 'str',
        'app_name': 'str',
        'app_icon': 'str',
        'is_show_form_border': 'bool',
        'is_quick_create': 'bool',
        'form_style': 'str',
        'form_width': 'str',
        'save_mode': 'str',
        'setting': 'dict(str, object)',
        'id': 'str',
        'company_id': 'str',
        'application_id': 'str',
        'create_time': 'float',
        'update_time': 'float',
        'create_account_id': 'str',
        'create_account_name': 'str',
        'update_account_id': 'str',
        'update_account_name': 'str',
        'app_color': 'str',
        'is_delete': 'bool'
    }

    attribute_map = {
        'module_name': 'moduleName',
        'module_icon': 'moduleIcon',
        'app_name': 'appName',
        'app_icon': 'appIcon',
        'is_show_form_border': 'isShowFormBorder',
        'is_quick_create': 'isQuickCreate',
        'form_style': 'formStyle',
        'form_width': 'formWidth',
        'save_mode': 'saveMode',
        'setting': 'setting',
        'id': 'id',
        'company_id': 'companyId',
        'application_id': 'applicationId',
        'create_time': 'createTime',
        'update_time': 'updateTime',
        'create_account_id': 'createAccountId',
        'create_account_name': 'createAccountName',
        'update_account_id': 'updateAccountId',
        'update_account_name': 'updateAccountName',
        'app_color': 'appColor',
        'is_delete': 'isDelete'
    }

    def __init__(self, module_name=None, module_icon=None, app_name=None, app_icon=None, is_show_form_border=None, is_quick_create=None, form_style=None, form_width=None, save_mode=None, setting=None, id=None, company_id=None, application_id=None, create_time=None, update_time=None, create_account_id=None, create_account_name=None, update_account_id=None, update_account_name=None, app_color=None, is_delete=None):  # noqa: E501
        """TableVO - a model defined in Swagger"""  # noqa: E501
        self._module_name = None
        self._module_icon = None
        self._app_name = None
        self._app_icon = None
        self._is_show_form_border = None
        self._is_quick_create = None
        self._form_style = None
        self._form_width = None
        self._save_mode = None
        self._setting = None
        self._id = None
        self._company_id = None
        self._application_id = None
        self._create_time = None
        self._update_time = None
        self._create_account_id = None
        self._create_account_name = None
        self._update_account_id = None
        self._update_account_name = None
        self._app_color = None
        self._is_delete = None
        self.discriminator = None
        if module_name is not None:
            self.module_name = module_name
        if module_icon is not None:
            self.module_icon = module_icon
        if app_name is not None:
            self.app_name = app_name
        if app_icon is not None:
            self.app_icon = app_icon
        if is_show_form_border is not None:
            self.is_show_form_border = is_show_form_border
        if is_quick_create is not None:
            self.is_quick_create = is_quick_create
        if form_style is not None:
            self.form_style = form_style
        if form_width is not None:
            self.form_width = form_width
        if save_mode is not None:
            self.save_mode = save_mode
        if setting is not None:
            self.setting = setting
        if id is not None:
            self.id = id
        if company_id is not None:
            self.company_id = company_id
        if application_id is not None:
            self.application_id = application_id
        if create_time is not None:
            self.create_time = create_time
        if update_time is not None:
            self.update_time = update_time
        if create_account_id is not None:
            self.create_account_id = create_account_id
        if create_account_name is not None:
            self.create_account_name = create_account_name
        if update_account_id is not None:
            self.update_account_id = update_account_id
        if update_account_name is not None:
            self.update_account_name = update_account_name
        if app_color is not None:
            self.app_color = app_color
        if is_delete is not None:
            self.is_delete = is_delete

    @property
    def module_name(self):
        """Gets the module_name of this TableVO.  # noqa: E501

        名称  # noqa: E501

        :return: The module_name of this TableVO.  # noqa: E501
        :rtype: str
        """
        return self._module_name

    @module_name.setter
    def module_name(self, module_name):
        """Sets the module_name of this TableVO.

        名称  # noqa: E501

        :param module_name: The module_name of this TableVO.  # noqa: E501
        :type: str
        """

        self._module_name = module_name

    @property
    def module_icon(self):
        """Gets the module_icon of this TableVO.  # noqa: E501

        图标  # noqa: E501

        :return: The module_icon of this TableVO.  # noqa: E501
        :rtype: str
        """
        return self._module_icon

    @module_icon.setter
    def module_icon(self, module_icon):
        """Sets the module_icon of this TableVO.

        图标  # noqa: E501

        :param module_icon: The module_icon of this TableVO.  # noqa: E501
        :type: str
        """

        self._module_icon = module_icon

    @property
    def app_name(self):
        """Gets the app_name of this TableVO.  # noqa: E501

        应用名称  # noqa: E501

        :return: The app_name of this TableVO.  # noqa: E501
        :rtype: str
        """
        return self._app_name

    @app_name.setter
    def app_name(self, app_name):
        """Sets the app_name of this TableVO.

        应用名称  # noqa: E501

        :param app_name: The app_name of this TableVO.  # noqa: E501
        :type: str
        """

        self._app_name = app_name

    @property
    def app_icon(self):
        """Gets the app_icon of this TableVO.  # noqa: E501

        应用图标  # noqa: E501

        :return: The app_icon of this TableVO.  # noqa: E501
        :rtype: str
        """
        return self._app_icon

    @app_icon.setter
    def app_icon(self, app_icon):
        """Sets the app_icon of this TableVO.

        应用图标  # noqa: E501

        :param app_icon: The app_icon of this TableVO.  # noqa: E501
        :type: str
        """

        self._app_icon = app_icon

    @property
    def is_show_form_border(self):
        """Gets the is_show_form_border of this TableVO.  # noqa: E501

        是否在卡片中显示表单边框  # noqa: E501

        :return: The is_show_form_border of this TableVO.  # noqa: E501
        :rtype: bool
        """
        return self._is_show_form_border

    @is_show_form_border.setter
    def is_show_form_border(self, is_show_form_border):
        """Sets the is_show_form_border of this TableVO.

        是否在卡片中显示表单边框  # noqa: E501

        :param is_show_form_border: The is_show_form_border of this TableVO.  # noqa: E501
        :type: bool
        """

        self._is_show_form_border = is_show_form_border

    @property
    def is_quick_create(self):
        """Gets the is_quick_create of this TableVO.  # noqa: E501

        是否支持快速创建  # noqa: E501

        :return: The is_quick_create of this TableVO.  # noqa: E501
        :rtype: bool
        """
        return self._is_quick_create

    @is_quick_create.setter
    def is_quick_create(self, is_quick_create):
        """Sets the is_quick_create of this TableVO.

        是否支持快速创建  # noqa: E501

        :param is_quick_create: The is_quick_create of this TableVO.  # noqa: E501
        :type: bool
        """

        self._is_quick_create = is_quick_create

    @property
    def form_style(self):
        """Gets the form_style of this TableVO.  # noqa: E501

        表单样式  # noqa: E501

        :return: The form_style of this TableVO.  # noqa: E501
        :rtype: str
        """
        return self._form_style

    @form_style.setter
    def form_style(self, form_style):
        """Sets the form_style of this TableVO.

        表单样式  # noqa: E501

        :param form_style: The form_style of this TableVO.  # noqa: E501
        :type: str
        """
        allowed_values = ["Simple", "Table", "SimpleRow"]  # noqa: E501
        if form_style not in allowed_values:
            raise ValueError(
                "Invalid value for `form_style` ({0}), must be one of {1}"  # noqa: E501
                .format(form_style, allowed_values)
            )

        self._form_style = form_style

    @property
    def form_width(self):
        """Gets the form_width of this TableVO.  # noqa: E501

        表单宽度  # noqa: E501

        :return: The form_width of this TableVO.  # noqa: E501
        :rtype: str
        """
        return self._form_width

    @form_width.setter
    def form_width(self, form_width):
        """Sets the form_width of this TableVO.

        表单宽度  # noqa: E501

        :param form_width: The form_width of this TableVO.  # noqa: E501
        :type: str
        """
        allowed_values = ["Normal", "Wide", "SuperWide", "Full"]  # noqa: E501
        if form_width not in allowed_values:
            raise ValueError(
                "Invalid value for `form_width` ({0}), must be one of {1}"  # noqa: E501
                .format(form_width, allowed_values)
            )

        self._form_width = form_width

    @property
    def save_mode(self):
        """Gets the save_mode of this TableVO.  # noqa: E501

        保存模式  # noqa: E501

        :return: The save_mode of this TableVO.  # noqa: E501
        :rtype: str
        """
        return self._save_mode

    @save_mode.setter
    def save_mode(self, save_mode):
        """Sets the save_mode of this TableVO.

        保存模式  # noqa: E501

        :param save_mode: The save_mode of this TableVO.  # noqa: E501
        :type: str
        """
        allowed_values = ["Field", "Form"]  # noqa: E501
        if save_mode not in allowed_values:
            raise ValueError(
                "Invalid value for `save_mode` ({0}), must be one of {1}"  # noqa: E501
                .format(save_mode, allowed_values)
            )

        self._save_mode = save_mode

    @property
    def setting(self):
        """Gets the setting of this TableVO.  # noqa: E501

        功能开关  # noqa: E501

        :return: The setting of this TableVO.  # noqa: E501
        :rtype: dict(str, object)
        """
        return self._setting

    @setting.setter
    def setting(self, setting):
        """Sets the setting of this TableVO.

        功能开关  # noqa: E501

        :param setting: The setting of this TableVO.  # noqa: E501
        :type: dict(str, object)
        """

        self._setting = setting

    @property
    def id(self):
        """Gets the id of this TableVO.  # noqa: E501

        ID  # noqa: E501

        :return: The id of this TableVO.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this TableVO.

        ID  # noqa: E501

        :param id: The id of this TableVO.  # noqa: E501
        :type: str
        """

        self._id = id

    @property
    def company_id(self):
        """Gets the company_id of this TableVO.  # noqa: E501

        团队ID  # noqa: E501

        :return: The company_id of this TableVO.  # noqa: E501
        :rtype: str
        """
        return self._company_id

    @company_id.setter
    def company_id(self, company_id):
        """Sets the company_id of this TableVO.

        团队ID  # noqa: E501

        :param company_id: The company_id of this TableVO.  # noqa: E501
        :type: str
        """

        self._company_id = company_id

    @property
    def application_id(self):
        """Gets the application_id of this TableVO.  # noqa: E501

        应用ID  # noqa: E501

        :return: The application_id of this TableVO.  # noqa: E501
        :rtype: str
        """
        return self._application_id

    @application_id.setter
    def application_id(self, application_id):
        """Sets the application_id of this TableVO.

        应用ID  # noqa: E501

        :param application_id: The application_id of this TableVO.  # noqa: E501
        :type: str
        """

        self._application_id = application_id

    @property
    def create_time(self):
        """Gets the create_time of this TableVO.  # noqa: E501

        创建时间  # noqa: E501

        :return: The create_time of this TableVO.  # noqa: E501
        :rtype: float
        """
        return self._create_time

    @create_time.setter
    def create_time(self, create_time):
        """Sets the create_time of this TableVO.

        创建时间  # noqa: E501

        :param create_time: The create_time of this TableVO.  # noqa: E501
        :type: float
        """

        self._create_time = create_time

    @property
    def update_time(self):
        """Gets the update_time of this TableVO.  # noqa: E501

        最后更新时间  # noqa: E501

        :return: The update_time of this TableVO.  # noqa: E501
        :rtype: float
        """
        return self._update_time

    @update_time.setter
    def update_time(self, update_time):
        """Sets the update_time of this TableVO.

        最后更新时间  # noqa: E501

        :param update_time: The update_time of this TableVO.  # noqa: E501
        :type: float
        """

        self._update_time = update_time

    @property
    def create_account_id(self):
        """Gets the create_account_id of this TableVO.  # noqa: E501

        创建人ID  # noqa: E501

        :return: The create_account_id of this TableVO.  # noqa: E501
        :rtype: str
        """
        return self._create_account_id

    @create_account_id.setter
    def create_account_id(self, create_account_id):
        """Sets the create_account_id of this TableVO.

        创建人ID  # noqa: E501

        :param create_account_id: The create_account_id of this TableVO.  # noqa: E501
        :type: str
        """

        self._create_account_id = create_account_id

    @property
    def create_account_name(self):
        """Gets the create_account_name of this TableVO.  # noqa: E501

        创建人名称  # noqa: E501

        :return: The create_account_name of this TableVO.  # noqa: E501
        :rtype: str
        """
        return self._create_account_name

    @create_account_name.setter
    def create_account_name(self, create_account_name):
        """Sets the create_account_name of this TableVO.

        创建人名称  # noqa: E501

        :param create_account_name: The create_account_name of this TableVO.  # noqa: E501
        :type: str
        """

        self._create_account_name = create_account_name

    @property
    def update_account_id(self):
        """Gets the update_account_id of this TableVO.  # noqa: E501

        最后更新人ID  # noqa: E501

        :return: The update_account_id of this TableVO.  # noqa: E501
        :rtype: str
        """
        return self._update_account_id

    @update_account_id.setter
    def update_account_id(self, update_account_id):
        """Sets the update_account_id of this TableVO.

        最后更新人ID  # noqa: E501

        :param update_account_id: The update_account_id of this TableVO.  # noqa: E501
        :type: str
        """

        self._update_account_id = update_account_id

    @property
    def update_account_name(self):
        """Gets the update_account_name of this TableVO.  # noqa: E501

        最后更新人名称  # noqa: E501

        :return: The update_account_name of this TableVO.  # noqa: E501
        :rtype: str
        """
        return self._update_account_name

    @update_account_name.setter
    def update_account_name(self, update_account_name):
        """Sets the update_account_name of this TableVO.

        最后更新人名称  # noqa: E501

        :param update_account_name: The update_account_name of this TableVO.  # noqa: E501
        :type: str
        """

        self._update_account_name = update_account_name

    @property
    def app_color(self):
        """Gets the app_color of this TableVO.  # noqa: E501

        应用颜色  # noqa: E501

        :return: The app_color of this TableVO.  # noqa: E501
        :rtype: str
        """
        return self._app_color

    @app_color.setter
    def app_color(self, app_color):
        """Sets the app_color of this TableVO.

        应用颜色  # noqa: E501

        :param app_color: The app_color of this TableVO.  # noqa: E501
        :type: str
        """

        self._app_color = app_color

    @property
    def is_delete(self):
        """Gets the is_delete of this TableVO.  # noqa: E501

        是否已删除  # noqa: E501

        :return: The is_delete of this TableVO.  # noqa: E501
        :rtype: bool
        """
        return self._is_delete

    @is_delete.setter
    def is_delete(self, is_delete):
        """Sets the is_delete of this TableVO.

        是否已删除  # noqa: E501

        :param is_delete: The is_delete of this TableVO.  # noqa: E501
        :type: bool
        """

        self._is_delete = is_delete

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(TableVO, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, TableVO):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
