# coding: utf-8

"""
    织信开放API接口

    织信开放API接口  # noqa: E501

    OpenAPI spec version: v2
    Contact: sales@conrerstone365.cn
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class WebsitePageCreateRequest(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'website_id': 'str',
        'name': 'str',
        'remark': 'str',
        'path': 'str',
        'draft_content': 'str',
        'is_hidden': 'bool'
    }

    attribute_map = {
        'website_id': 'websiteId',
        'name': 'name',
        'remark': 'remark',
        'path': 'path',
        'draft_content': 'draftContent',
        'is_hidden': 'isHidden'
    }

    def __init__(self, website_id=None, name=None, remark=None, path=None, draft_content=None, is_hidden=None):  # noqa: E501
        """WebsitePageCreateRequest - a model defined in Swagger"""  # noqa: E501
        self._website_id = None
        self._name = None
        self._remark = None
        self._path = None
        self._draft_content = None
        self._is_hidden = None
        self.discriminator = None
        self.website_id = website_id
        self.name = name
        if remark is not None:
            self.remark = remark
        if path is not None:
            self.path = path
        if draft_content is not None:
            self.draft_content = draft_content
        if is_hidden is not None:
            self.is_hidden = is_hidden

    @property
    def website_id(self):
        """Gets the website_id of this WebsitePageCreateRequest.  # noqa: E501

        网站ID  # noqa: E501

        :return: The website_id of this WebsitePageCreateRequest.  # noqa: E501
        :rtype: str
        """
        return self._website_id

    @website_id.setter
    def website_id(self, website_id):
        """Sets the website_id of this WebsitePageCreateRequest.

        网站ID  # noqa: E501

        :param website_id: The website_id of this WebsitePageCreateRequest.  # noqa: E501
        :type: str
        """
        if website_id is None:
            raise ValueError("Invalid value for `website_id`, must not be `None`")  # noqa: E501

        self._website_id = website_id

    @property
    def name(self):
        """Gets the name of this WebsitePageCreateRequest.  # noqa: E501

        名称  # noqa: E501

        :return: The name of this WebsitePageCreateRequest.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this WebsitePageCreateRequest.

        名称  # noqa: E501

        :param name: The name of this WebsitePageCreateRequest.  # noqa: E501
        :type: str
        """
        if name is None:
            raise ValueError("Invalid value for `name`, must not be `None`")  # noqa: E501

        self._name = name

    @property
    def remark(self):
        """Gets the remark of this WebsitePageCreateRequest.  # noqa: E501

        备注  # noqa: E501

        :return: The remark of this WebsitePageCreateRequest.  # noqa: E501
        :rtype: str
        """
        return self._remark

    @remark.setter
    def remark(self, remark):
        """Sets the remark of this WebsitePageCreateRequest.

        备注  # noqa: E501

        :param remark: The remark of this WebsitePageCreateRequest.  # noqa: E501
        :type: str
        """

        self._remark = remark

    @property
    def path(self):
        """Gets the path of this WebsitePageCreateRequest.  # noqa: E501

        路径  # noqa: E501

        :return: The path of this WebsitePageCreateRequest.  # noqa: E501
        :rtype: str
        """
        return self._path

    @path.setter
    def path(self, path):
        """Sets the path of this WebsitePageCreateRequest.

        路径  # noqa: E501

        :param path: The path of this WebsitePageCreateRequest.  # noqa: E501
        :type: str
        """

        self._path = path

    @property
    def draft_content(self):
        """Gets the draft_content of this WebsitePageCreateRequest.  # noqa: E501

        草稿内容  # noqa: E501

        :return: The draft_content of this WebsitePageCreateRequest.  # noqa: E501
        :rtype: str
        """
        return self._draft_content

    @draft_content.setter
    def draft_content(self, draft_content):
        """Sets the draft_content of this WebsitePageCreateRequest.

        草稿内容  # noqa: E501

        :param draft_content: The draft_content of this WebsitePageCreateRequest.  # noqa: E501
        :type: str
        """

        self._draft_content = draft_content

    @property
    def is_hidden(self):
        """Gets the is_hidden of this WebsitePageCreateRequest.  # noqa: E501

        是否隐藏  # noqa: E501

        :return: The is_hidden of this WebsitePageCreateRequest.  # noqa: E501
        :rtype: bool
        """
        return self._is_hidden

    @is_hidden.setter
    def is_hidden(self, is_hidden):
        """Sets the is_hidden of this WebsitePageCreateRequest.

        是否隐藏  # noqa: E501

        :param is_hidden: The is_hidden of this WebsitePageCreateRequest.  # noqa: E501
        :type: bool
        """

        self._is_hidden = is_hidden

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(WebsitePageCreateRequest, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, WebsitePageCreateRequest):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
