# coding: utf-8

"""
    织信开放API接口

    织信开放API接口  # noqa: E501

    OpenAPI spec version: v2
    Contact: sales@conrerstone365.cn
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

import pprint
import re  # noqa: F401

import six

class WebsitePageVO(object):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """
    """
    Attributes:
      swagger_types (dict): The key is attribute name
                            and the value is attribute type.
      attribute_map (dict): The key is attribute name
                            and the value is json key in definition.
    """
    swagger_types = {
        'website_id': 'str',
        'name': 'str',
        'remark': 'str',
        'path': 'str',
        'cover_id': 'str',
        'content': 'str',
        'draft_content': 'str',
        'is_publish': 'bool',
        'is_hidden': 'bool',
        'id': 'str',
        'company_id': 'str',
        'application_id': 'str',
        'create_time': 'float',
        'update_time': 'float',
        'create_account_id': 'str',
        'create_account_name': 'str',
        'update_account_id': 'str',
        'update_account_name': 'str',
        'app_name': 'str',
        'app_color': 'str',
        'app_icon': 'str',
        'is_delete': 'bool'
    }

    attribute_map = {
        'website_id': 'websiteId',
        'name': 'name',
        'remark': 'remark',
        'path': 'path',
        'cover_id': 'coverId',
        'content': 'content',
        'draft_content': 'draftContent',
        'is_publish': 'isPublish',
        'is_hidden': 'isHidden',
        'id': 'id',
        'company_id': 'companyId',
        'application_id': 'applicationId',
        'create_time': 'createTime',
        'update_time': 'updateTime',
        'create_account_id': 'createAccountId',
        'create_account_name': 'createAccountName',
        'update_account_id': 'updateAccountId',
        'update_account_name': 'updateAccountName',
        'app_name': 'appName',
        'app_color': 'appColor',
        'app_icon': 'appIcon',
        'is_delete': 'isDelete'
    }

    def __init__(self, website_id=None, name=None, remark=None, path=None, cover_id=None, content=None, draft_content=None, is_publish=None, is_hidden=None, id=None, company_id=None, application_id=None, create_time=None, update_time=None, create_account_id=None, create_account_name=None, update_account_id=None, update_account_name=None, app_name=None, app_color=None, app_icon=None, is_delete=None):  # noqa: E501
        """WebsitePageVO - a model defined in Swagger"""  # noqa: E501
        self._website_id = None
        self._name = None
        self._remark = None
        self._path = None
        self._cover_id = None
        self._content = None
        self._draft_content = None
        self._is_publish = None
        self._is_hidden = None
        self._id = None
        self._company_id = None
        self._application_id = None
        self._create_time = None
        self._update_time = None
        self._create_account_id = None
        self._create_account_name = None
        self._update_account_id = None
        self._update_account_name = None
        self._app_name = None
        self._app_color = None
        self._app_icon = None
        self._is_delete = None
        self.discriminator = None
        if website_id is not None:
            self.website_id = website_id
        if name is not None:
            self.name = name
        if remark is not None:
            self.remark = remark
        if path is not None:
            self.path = path
        if cover_id is not None:
            self.cover_id = cover_id
        if content is not None:
            self.content = content
        if draft_content is not None:
            self.draft_content = draft_content
        if is_publish is not None:
            self.is_publish = is_publish
        if is_hidden is not None:
            self.is_hidden = is_hidden
        if id is not None:
            self.id = id
        if company_id is not None:
            self.company_id = company_id
        if application_id is not None:
            self.application_id = application_id
        if create_time is not None:
            self.create_time = create_time
        if update_time is not None:
            self.update_time = update_time
        if create_account_id is not None:
            self.create_account_id = create_account_id
        if create_account_name is not None:
            self.create_account_name = create_account_name
        if update_account_id is not None:
            self.update_account_id = update_account_id
        if update_account_name is not None:
            self.update_account_name = update_account_name
        if app_name is not None:
            self.app_name = app_name
        if app_color is not None:
            self.app_color = app_color
        if app_icon is not None:
            self.app_icon = app_icon
        if is_delete is not None:
            self.is_delete = is_delete

    @property
    def website_id(self):
        """Gets the website_id of this WebsitePageVO.  # noqa: E501

        网站模块ID  # noqa: E501

        :return: The website_id of this WebsitePageVO.  # noqa: E501
        :rtype: str
        """
        return self._website_id

    @website_id.setter
    def website_id(self, website_id):
        """Sets the website_id of this WebsitePageVO.

        网站模块ID  # noqa: E501

        :param website_id: The website_id of this WebsitePageVO.  # noqa: E501
        :type: str
        """

        self._website_id = website_id

    @property
    def name(self):
        """Gets the name of this WebsitePageVO.  # noqa: E501

        名称  # noqa: E501

        :return: The name of this WebsitePageVO.  # noqa: E501
        :rtype: str
        """
        return self._name

    @name.setter
    def name(self, name):
        """Sets the name of this WebsitePageVO.

        名称  # noqa: E501

        :param name: The name of this WebsitePageVO.  # noqa: E501
        :type: str
        """

        self._name = name

    @property
    def remark(self):
        """Gets the remark of this WebsitePageVO.  # noqa: E501

        备注  # noqa: E501

        :return: The remark of this WebsitePageVO.  # noqa: E501
        :rtype: str
        """
        return self._remark

    @remark.setter
    def remark(self, remark):
        """Sets the remark of this WebsitePageVO.

        备注  # noqa: E501

        :param remark: The remark of this WebsitePageVO.  # noqa: E501
        :type: str
        """

        self._remark = remark

    @property
    def path(self):
        """Gets the path of this WebsitePageVO.  # noqa: E501

        访问路径  # noqa: E501

        :return: The path of this WebsitePageVO.  # noqa: E501
        :rtype: str
        """
        return self._path

    @path.setter
    def path(self, path):
        """Sets the path of this WebsitePageVO.

        访问路径  # noqa: E501

        :param path: The path of this WebsitePageVO.  # noqa: E501
        :type: str
        """

        self._path = path

    @property
    def cover_id(self):
        """Gets the cover_id of this WebsitePageVO.  # noqa: E501

        封面  # noqa: E501

        :return: The cover_id of this WebsitePageVO.  # noqa: E501
        :rtype: str
        """
        return self._cover_id

    @cover_id.setter
    def cover_id(self, cover_id):
        """Sets the cover_id of this WebsitePageVO.

        封面  # noqa: E501

        :param cover_id: The cover_id of this WebsitePageVO.  # noqa: E501
        :type: str
        """

        self._cover_id = cover_id

    @property
    def content(self):
        """Gets the content of this WebsitePageVO.  # noqa: E501

        内容  # noqa: E501

        :return: The content of this WebsitePageVO.  # noqa: E501
        :rtype: str
        """
        return self._content

    @content.setter
    def content(self, content):
        """Sets the content of this WebsitePageVO.

        内容  # noqa: E501

        :param content: The content of this WebsitePageVO.  # noqa: E501
        :type: str
        """

        self._content = content

    @property
    def draft_content(self):
        """Gets the draft_content of this WebsitePageVO.  # noqa: E501

        草稿内容  # noqa: E501

        :return: The draft_content of this WebsitePageVO.  # noqa: E501
        :rtype: str
        """
        return self._draft_content

    @draft_content.setter
    def draft_content(self, draft_content):
        """Sets the draft_content of this WebsitePageVO.

        草稿内容  # noqa: E501

        :param draft_content: The draft_content of this WebsitePageVO.  # noqa: E501
        :type: str
        """

        self._draft_content = draft_content

    @property
    def is_publish(self):
        """Gets the is_publish of this WebsitePageVO.  # noqa: E501

        是否发布  # noqa: E501

        :return: The is_publish of this WebsitePageVO.  # noqa: E501
        :rtype: bool
        """
        return self._is_publish

    @is_publish.setter
    def is_publish(self, is_publish):
        """Sets the is_publish of this WebsitePageVO.

        是否发布  # noqa: E501

        :param is_publish: The is_publish of this WebsitePageVO.  # noqa: E501
        :type: bool
        """

        self._is_publish = is_publish

    @property
    def is_hidden(self):
        """Gets the is_hidden of this WebsitePageVO.  # noqa: E501

        是否隐藏  # noqa: E501

        :return: The is_hidden of this WebsitePageVO.  # noqa: E501
        :rtype: bool
        """
        return self._is_hidden

    @is_hidden.setter
    def is_hidden(self, is_hidden):
        """Sets the is_hidden of this WebsitePageVO.

        是否隐藏  # noqa: E501

        :param is_hidden: The is_hidden of this WebsitePageVO.  # noqa: E501
        :type: bool
        """

        self._is_hidden = is_hidden

    @property
    def id(self):
        """Gets the id of this WebsitePageVO.  # noqa: E501

        ID  # noqa: E501

        :return: The id of this WebsitePageVO.  # noqa: E501
        :rtype: str
        """
        return self._id

    @id.setter
    def id(self, id):
        """Sets the id of this WebsitePageVO.

        ID  # noqa: E501

        :param id: The id of this WebsitePageVO.  # noqa: E501
        :type: str
        """

        self._id = id

    @property
    def company_id(self):
        """Gets the company_id of this WebsitePageVO.  # noqa: E501

        团队ID  # noqa: E501

        :return: The company_id of this WebsitePageVO.  # noqa: E501
        :rtype: str
        """
        return self._company_id

    @company_id.setter
    def company_id(self, company_id):
        """Sets the company_id of this WebsitePageVO.

        团队ID  # noqa: E501

        :param company_id: The company_id of this WebsitePageVO.  # noqa: E501
        :type: str
        """

        self._company_id = company_id

    @property
    def application_id(self):
        """Gets the application_id of this WebsitePageVO.  # noqa: E501

        应用ID  # noqa: E501

        :return: The application_id of this WebsitePageVO.  # noqa: E501
        :rtype: str
        """
        return self._application_id

    @application_id.setter
    def application_id(self, application_id):
        """Sets the application_id of this WebsitePageVO.

        应用ID  # noqa: E501

        :param application_id: The application_id of this WebsitePageVO.  # noqa: E501
        :type: str
        """

        self._application_id = application_id

    @property
    def create_time(self):
        """Gets the create_time of this WebsitePageVO.  # noqa: E501

        创建时间  # noqa: E501

        :return: The create_time of this WebsitePageVO.  # noqa: E501
        :rtype: float
        """
        return self._create_time

    @create_time.setter
    def create_time(self, create_time):
        """Sets the create_time of this WebsitePageVO.

        创建时间  # noqa: E501

        :param create_time: The create_time of this WebsitePageVO.  # noqa: E501
        :type: float
        """

        self._create_time = create_time

    @property
    def update_time(self):
        """Gets the update_time of this WebsitePageVO.  # noqa: E501

        最后更新时间  # noqa: E501

        :return: The update_time of this WebsitePageVO.  # noqa: E501
        :rtype: float
        """
        return self._update_time

    @update_time.setter
    def update_time(self, update_time):
        """Sets the update_time of this WebsitePageVO.

        最后更新时间  # noqa: E501

        :param update_time: The update_time of this WebsitePageVO.  # noqa: E501
        :type: float
        """

        self._update_time = update_time

    @property
    def create_account_id(self):
        """Gets the create_account_id of this WebsitePageVO.  # noqa: E501

        创建人ID  # noqa: E501

        :return: The create_account_id of this WebsitePageVO.  # noqa: E501
        :rtype: str
        """
        return self._create_account_id

    @create_account_id.setter
    def create_account_id(self, create_account_id):
        """Sets the create_account_id of this WebsitePageVO.

        创建人ID  # noqa: E501

        :param create_account_id: The create_account_id of this WebsitePageVO.  # noqa: E501
        :type: str
        """

        self._create_account_id = create_account_id

    @property
    def create_account_name(self):
        """Gets the create_account_name of this WebsitePageVO.  # noqa: E501

        创建人名称  # noqa: E501

        :return: The create_account_name of this WebsitePageVO.  # noqa: E501
        :rtype: str
        """
        return self._create_account_name

    @create_account_name.setter
    def create_account_name(self, create_account_name):
        """Sets the create_account_name of this WebsitePageVO.

        创建人名称  # noqa: E501

        :param create_account_name: The create_account_name of this WebsitePageVO.  # noqa: E501
        :type: str
        """

        self._create_account_name = create_account_name

    @property
    def update_account_id(self):
        """Gets the update_account_id of this WebsitePageVO.  # noqa: E501

        最后更新人ID  # noqa: E501

        :return: The update_account_id of this WebsitePageVO.  # noqa: E501
        :rtype: str
        """
        return self._update_account_id

    @update_account_id.setter
    def update_account_id(self, update_account_id):
        """Sets the update_account_id of this WebsitePageVO.

        最后更新人ID  # noqa: E501

        :param update_account_id: The update_account_id of this WebsitePageVO.  # noqa: E501
        :type: str
        """

        self._update_account_id = update_account_id

    @property
    def update_account_name(self):
        """Gets the update_account_name of this WebsitePageVO.  # noqa: E501

        最后更新人名称  # noqa: E501

        :return: The update_account_name of this WebsitePageVO.  # noqa: E501
        :rtype: str
        """
        return self._update_account_name

    @update_account_name.setter
    def update_account_name(self, update_account_name):
        """Sets the update_account_name of this WebsitePageVO.

        最后更新人名称  # noqa: E501

        :param update_account_name: The update_account_name of this WebsitePageVO.  # noqa: E501
        :type: str
        """

        self._update_account_name = update_account_name

    @property
    def app_name(self):
        """Gets the app_name of this WebsitePageVO.  # noqa: E501

        应用名称  # noqa: E501

        :return: The app_name of this WebsitePageVO.  # noqa: E501
        :rtype: str
        """
        return self._app_name

    @app_name.setter
    def app_name(self, app_name):
        """Sets the app_name of this WebsitePageVO.

        应用名称  # noqa: E501

        :param app_name: The app_name of this WebsitePageVO.  # noqa: E501
        :type: str
        """

        self._app_name = app_name

    @property
    def app_color(self):
        """Gets the app_color of this WebsitePageVO.  # noqa: E501

        应用颜色  # noqa: E501

        :return: The app_color of this WebsitePageVO.  # noqa: E501
        :rtype: str
        """
        return self._app_color

    @app_color.setter
    def app_color(self, app_color):
        """Sets the app_color of this WebsitePageVO.

        应用颜色  # noqa: E501

        :param app_color: The app_color of this WebsitePageVO.  # noqa: E501
        :type: str
        """

        self._app_color = app_color

    @property
    def app_icon(self):
        """Gets the app_icon of this WebsitePageVO.  # noqa: E501

        应用图标  # noqa: E501

        :return: The app_icon of this WebsitePageVO.  # noqa: E501
        :rtype: str
        """
        return self._app_icon

    @app_icon.setter
    def app_icon(self, app_icon):
        """Sets the app_icon of this WebsitePageVO.

        应用图标  # noqa: E501

        :param app_icon: The app_icon of this WebsitePageVO.  # noqa: E501
        :type: str
        """

        self._app_icon = app_icon

    @property
    def is_delete(self):
        """Gets the is_delete of this WebsitePageVO.  # noqa: E501

        是否已删除  # noqa: E501

        :return: The is_delete of this WebsitePageVO.  # noqa: E501
        :rtype: bool
        """
        return self._is_delete

    @is_delete.setter
    def is_delete(self, is_delete):
        """Sets the is_delete of this WebsitePageVO.

        是否已删除  # noqa: E501

        :param is_delete: The is_delete of this WebsitePageVO.  # noqa: E501
        :type: bool
        """

        self._is_delete = is_delete

    def to_dict(self):
        """Returns the model properties as a dict"""
        result = {}

        for attr, _ in six.iteritems(self.swagger_types):
            value = getattr(self, attr)
            if isinstance(value, list):
                result[attr] = list(map(
                    lambda x: x.to_dict() if hasattr(x, "to_dict") else x,
                    value
                ))
            elif hasattr(value, "to_dict"):
                result[attr] = value.to_dict()
            elif isinstance(value, dict):
                result[attr] = dict(map(
                    lambda item: (item[0], item[1].to_dict())
                    if hasattr(item[1], "to_dict") else item,
                    value.items()
                ))
            else:
                result[attr] = value
        if issubclass(WebsitePageVO, dict):
            for key, value in self.items():
                result[key] = value

        return result

    def to_str(self):
        """Returns the string representation of the model"""
        return pprint.pformat(self.to_dict())

    def __repr__(self):
        """For `print` and `pprint`"""
        return self.to_str()

    def __eq__(self, other):
        """Returns true if both objects are equal"""
        if not isinstance(other, WebsitePageVO):
            return False

        return self.__dict__ == other.__dict__

    def __ne__(self, other):
        """Returns true if both objects are not equal"""
        return not self == other
