# coding: utf-8

"""
    织信开放API接口

    织信开放API接口  # noqa: E501

    OpenAPI spec version: v2
    Contact: sales@conrerstone365.cn
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.app_script_create_request import AppScriptCreateRequest  # noqa: E501
from swagger_client.rest import ApiException


class TestAppScriptCreateRequest(unittest.TestCase):
    """AppScriptCreateRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAppScriptCreateRequest(self):
        """Test AppScriptCreateRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.app_script_create_request.AppScriptCreateRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
