# coding: utf-8

"""
    织信开放API接口

    织信开放API接口  # noqa: E501

    OpenAPI spec version: v2
    Contact: sales@conrerstone365.cn
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.app_api import AppApi  # noqa: E501
from swagger_client.rest import ApiException


class TestAppApi(unittest.TestCase):
    """AppApi unit test stubs"""

    def setUp(self):
        self.api = AppApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_app_auth(self):
        """Test case for app_auth

        应用鉴权  # noqa: E501
        """
        pass

    def test_app_delete(self):
        """Test case for app_delete

        删除应用  # noqa: E501
        """
        pass

    def test_app_import(self):
        """Test case for app_import

        通过ima文件安装应用  # noqa: E501
        """
        pass

    def test_app_install_template(self):
        """Test case for app_install_template

        通过应用模板安装应用  # noqa: E501
        """
        pass

    def test_app_list(self):
        """Test case for app_list

        应用列表  # noqa: E501
        """
        pass

    def test_app_member_create(self):
        """Test case for app_member_create

        创建应用成员  # noqa: E501
        """
        pass

    def test_app_member_delete(self):
        """Test case for app_member_delete

        从应用移除成员  # noqa: E501
        """
        pass

    def test_app_member_get(self):
        """Test case for app_member_get

        查询应用成员  # noqa: E501
        """
        pass

    def test_app_member_list(self):
        """Test case for app_member_list

        获取成员列表  # noqa: E501
        """
        pass

    def test_app_member_role_create(self):
        """Test case for app_member_role_create

        创建应用角色  # noqa: E501
        """
        pass

    def test_app_member_role_delete(self):
        """Test case for app_member_role_delete

        删除应用角色  # noqa: E501
        """
        pass

    def test_app_member_role_get(self):
        """Test case for app_member_role_get

        获取应用角色  # noqa: E501
        """
        pass

    def test_app_member_role_list(self):
        """Test case for app_member_role_list

        获取应用角色列表  # noqa: E501
        """
        pass

    def test_app_member_role_update(self):
        """Test case for app_member_role_update

        更新应用角色  # noqa: E501
        """
        pass

    def test_app_member_update(self):
        """Test case for app_member_update

        更新应用成员  # noqa: E501
        """
        pass

    def test_app_module_get(self):
        """Test case for app_module_get

        应用模块查询  # noqa: E501
        """
        pass

    def test_app_module_list(self):
        """Test case for app_module_list

        应用模块列表  # noqa: E501
        """
        pass

    def test_app_refresh_token(self):
        """Test case for app_refresh_token

        刷新应用accessToken  # noqa: E501
        """
        pass

    def test_app_script_create(self):
        """Test case for app_script_create

        创建脚本  # noqa: E501
        """
        pass

    def test_app_script_delete(self):
        """Test case for app_script_delete

        删除脚本  # noqa: E501
        """
        pass

    def test_app_script_list(self):
        """Test case for app_script_list

        查询脚本列表  # noqa: E501
        """
        pass

    def test_app_script_load(self):
        """Test case for app_script_load

        装载脚本  # noqa: E501
        """
        pass

    def test_app_script_update(self):
        """Test case for app_script_update

        编辑脚本  # noqa: E501
        """
        pass

    def test_app_token(self):
        """Test case for app_token

        获取应用accessToken  # noqa: E501
        """
        pass

    def test_app_version(self):
        """Test case for app_version

        系统版本号  # noqa: E501
        """
        pass

    def test_table_get(self):
        """Test case for table_get

        查询数据表  # noqa: E501
        """
        pass

    def test_table_list(self):
        """Test case for table_list

        数据表列表  # noqa: E501
        """
        pass

    def test_table_record_batch_create(self):
        """Test case for table_record_batch_create

        批量创建数据表记录  # noqa: E501
        """
        pass

    def test_table_record_batch_delete(self):
        """Test case for table_record_batch_delete

        批量删除数据表记录  # noqa: E501
        """
        pass

    def test_table_record_batch_update(self):
        """Test case for table_record_batch_update

        批量编辑数据表记录  # noqa: E501
        """
        pass

    def test_table_record_create(self):
        """Test case for table_record_create

        创建数据表记录  # noqa: E501
        """
        pass

    def test_table_record_delete(self):
        """Test case for table_record_delete

        删除数据表记录  # noqa: E501
        """
        pass

    def test_table_record_list(self):
        """Test case for table_record_list

        查询数据表记录列表  # noqa: E501
        """
        pass

    def test_table_record_update(self):
        """Test case for table_record_update

        编辑数据表记录  # noqa: E501
        """
        pass

    def test_table_workflow_chart_get(self):
        """Test case for table_workflow_chart_get

        通过id查询审批流程图详情  # noqa: E501
        """
        pass

    def test_table_workflow_chart_list(self):
        """Test case for table_workflow_chart_list

        查询审批流程图列表  # noqa: E501
        """
        pass

    def test_table_workflow_get(self):
        """Test case for table_workflow_get

        通过id查询审批流程详情  # noqa: E501
        """
        pass

    def test_table_workflow_instance_cancel(self):
        """Test case for table_workflow_instance_cancel

        取消审批流程  # noqa: E501
        """
        pass

    def test_table_workflow_instance_create(self):
        """Test case for table_workflow_instance_create

        发起审批流程  # noqa: E501
        """
        pass

    def test_table_workflow_instance_get(self):
        """Test case for table_workflow_instance_get

        通过ID查询审批流程实例详情  # noqa: E501
        """
        pass

    def test_table_workflow_instance_list(self):
        """Test case for table_workflow_instance_list

        查询审批流程实例列表  # noqa: E501
        """
        pass

    def test_table_workflow_instance_node_get(self):
        """Test case for table_workflow_instance_node_get

        通过ID查询审批流程实例节点详情  # noqa: E501
        """
        pass

    def test_table_workflow_instance_node_list(self):
        """Test case for table_workflow_instance_node_list

        查询审批流程实例节点列表  # noqa: E501
        """
        pass

    def test_table_workflow_instance_node_owner_agree(self):
        """Test case for table_workflow_instance_node_owner_agree

        同意审批流程  # noqa: E501
        """
        pass

    def test_table_workflow_instance_node_owner_get(self):
        """Test case for table_workflow_instance_node_owner_get

        通过ID查询审批流程实例节点审批人  # noqa: E501
        """
        pass

    def test_table_workflow_instance_node_owner_list(self):
        """Test case for table_workflow_instance_node_owner_list

        查询审批流程实例节点审批人列表  # noqa: E501
        """
        pass

    def test_table_workflow_instance_node_owner_refuse(self):
        """Test case for table_workflow_instance_node_owner_refuse

        拒绝审批流程  # noqa: E501
        """
        pass

    def test_table_workflow_instance_node_owner_rollback(self):
        """Test case for table_workflow_instance_node_owner_rollback

        回退审批流程  # noqa: E501
        """
        pass

    def test_table_workflow_instance_node_owner_transfer(self):
        """Test case for table_workflow_instance_node_owner_transfer

        转交审批流程  # noqa: E501
        """
        pass

    def test_table_workflow_instance_set_owner(self):
        """Test case for table_workflow_instance_set_owner

        设置审批人  # noqa: E501
        """
        pass

    def test_table_workflow_list(self):
        """Test case for table_workflow_list

        查询审批流程列表  # noqa: E501
        """
        pass

    def test_website_material_create(self):
        """Test case for website_material_create

        创建网站模块素材  # noqa: E501
        """
        pass

    def test_website_material_delete(self):
        """Test case for website_material_delete

        删除网站模块素材  # noqa: E501
        """
        pass

    def test_website_material_list(self):
        """Test case for website_material_list

        查询网站模块素材列表  # noqa: E501
        """
        pass

    def test_website_material_update(self):
        """Test case for website_material_update

        更新网站模块素材  # noqa: E501
        """
        pass

    def test_website_page_create(self):
        """Test case for website_page_create

        创建网站模块页面  # noqa: E501
        """
        pass

    def test_website_page_delete(self):
        """Test case for website_page_delete

        删除网站模块页面  # noqa: E501
        """
        pass

    def test_website_page_get(self):
        """Test case for website_page_get

        通过ID查询网站模板页面  # noqa: E501
        """
        pass

    def test_website_page_list(self):
        """Test case for website_page_list

        查询网站模板页面列表  # noqa: E501
        """
        pass

    def test_website_page_publish(self):
        """Test case for website_page_publish

        发布网站模块页面  # noqa: E501
        """
        pass

    def test_website_page_update(self):
        """Test case for website_page_update

        编辑网站模块页面  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
