# coding: utf-8

"""
    织信开放API接口

    织信开放API接口  # noqa: E501

    OpenAPI spec version: v2
    Contact: sales@conrerstone365.cn
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.app_install_template_request import AppInstallTemplateRequest  # noqa: E501
from swagger_client.rest import ApiException


class TestAppInstallTemplateRequest(unittest.TestCase):
    """AppInstallTemplateRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAppInstallTemplateRequest(self):
        """Test AppInstallTemplateRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.app_install_template_request.AppInstallTemplateRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
