# coding: utf-8

"""
    织信开放API接口

    织信开放API接口  # noqa: E501

    OpenAPI spec version: v2
    Contact: sales@conrerstone365.cn
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.admin_app_template_update_response import AdminAppTemplateUpdateResponse  # noqa: E501
from swagger_client.rest import ApiException


class TestAdminAppTemplateUpdateResponse(unittest.TestCase):
    """AdminAppTemplateUpdateResponse unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testAdminAppTemplateUpdateResponse(self):
        """Test AdminAppTemplateUpdateResponse"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.admin_app_template_update_response.AdminAppTemplateUpdateResponse()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
