# coding: utf-8

"""
    织信开放API接口

    织信开放API接口  # noqa: E501

    OpenAPI spec version: v2
    Contact: sales@conrerstone365.cn
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.models.company_update_logo_request import CompanyUpdateLogoRequest  # noqa: E501
from swagger_client.rest import ApiException


class TestCompanyUpdateLogoRequest(unittest.TestCase):
    """CompanyUpdateLogoRequest unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testCompanyUpdateLogoRequest(self):
        """Test CompanyUpdateLogoRequest"""
        # FIXME: construct object with mandatory attributes with example values
        # model = swagger_client.models.company_update_logo_request.CompanyUpdateLogoRequest()  # noqa: E501
        pass


if __name__ == '__main__':
    unittest.main()
