# coding: utf-8

"""
    织信开放API接口

    织信开放API接口  # noqa: E501

    OpenAPI spec version: v2
    Contact: sales@conrerstone365.cn
    Generated by: https://github.com/swagger-api/swagger-codegen.git
"""

from __future__ import absolute_import

import unittest

import swagger_client
from swagger_client.api.company_api import CompanyApi  # noqa: E501
from swagger_client.rest import ApiException


class TestCompanyApi(unittest.TestCase):
    """CompanyApi unit test stubs"""

    def setUp(self):
        self.api = CompanyApi()  # noqa: E501

    def tearDown(self):
        pass

    def test_company_department_create(self):
        """Test case for company_department_create

        创建部门  # noqa: E501
        """
        pass

    def test_company_department_delete(self):
        """Test case for company_department_delete

        删除部门  # noqa: E501
        """
        pass

    def test_company_department_list(self):
        """Test case for company_department_list

        获取部门列表  # noqa: E501
        """
        pass

    def test_company_department_update(self):
        """Test case for company_department_update

        更新部门  # noqa: E501
        """
        pass

    def test_company_get(self):
        """Test case for company_get

        获取当前团队信息  # noqa: E501
        """
        pass

    def test_company_member_batch_delete(self):
        """Test case for company_member_batch_delete

        从团队批量移除成员  # noqa: E501
        """
        pass

    def test_company_member_get(self):
        """Test case for company_member_get

        根据token查询用户信息  # noqa: E501
        """
        pass

    def test_company_member_list(self):
        """Test case for company_member_list

        获取成员列表  # noqa: E501
        """
        pass

    def test_company_member_role_create(self):
        """Test case for company_member_role_create

        创建角色  # noqa: E501
        """
        pass

    def test_company_member_role_delete(self):
        """Test case for company_member_role_delete

        删除角色  # noqa: E501
        """
        pass

    def test_company_member_role_list(self):
        """Test case for company_member_role_list

        获取角色列表  # noqa: E501
        """
        pass

    def test_company_member_role_update(self):
        """Test case for company_member_role_update

        更新角色  # noqa: E501
        """
        pass

    def test_company_member_update(self):
        """Test case for company_member_update

        更新成员信息  # noqa: E501
        """
        pass

    def test_company_refresh_token(self):
        """Test case for company_refresh_token

        刷新团队token  # noqa: E501
        """
        pass

    def test_company_token(self):
        """Test case for company_token

        获取团队token  # noqa: E501
        """
        pass

    def test_company_update_logo(self):
        """Test case for company_update_logo

        修改团队logo  # noqa: E501
        """
        pass


if __name__ == '__main__':
    unittest.main()
